// Code generated by ent, DO NOT EDIT.

package hubcommunityworker

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublisherUserID applies equality check predicate on the "publisher_user_id" field. It's identical to PublisherUserIDEQ.
func PublisherUserID(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldPublisherUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldDescription, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldDomain, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldScope, v))
}

// InstallCount applies equality check predicate on the "install_count" field. It's identical to InstallCountEQ.
func InstallCount(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldInstallCount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublisherUserIDEQ applies the EQ predicate on the "publisher_user_id" field.
func PublisherUserIDEQ(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldPublisherUserID, v))
}

// PublisherUserIDNEQ applies the NEQ predicate on the "publisher_user_id" field.
func PublisherUserIDNEQ(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldPublisherUserID, v))
}

// PublisherUserIDIn applies the In predicate on the "publisher_user_id" field.
func PublisherUserIDIn(vs ...int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldPublisherUserID, vs...))
}

// PublisherUserIDNotIn applies the NotIn predicate on the "publisher_user_id" field.
func PublisherUserIDNotIn(vs ...int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldPublisherUserID, vs...))
}

// PublisherUserIDGT applies the GT predicate on the "publisher_user_id" field.
func PublisherUserIDGT(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldPublisherUserID, v))
}

// PublisherUserIDGTE applies the GTE predicate on the "publisher_user_id" field.
func PublisherUserIDGTE(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldPublisherUserID, v))
}

// PublisherUserIDLT applies the LT predicate on the "publisher_user_id" field.
func PublisherUserIDLT(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldPublisherUserID, v))
}

// PublisherUserIDLTE applies the LTE predicate on the "publisher_user_id" field.
func PublisherUserIDLTE(v int64) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldPublisherUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContainsFold(FieldDescription, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContainsFold(FieldDomain, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeIsNil applies the IsNil predicate on the "scope" field.
func ScopeIsNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIsNull(FieldScope))
}

// ScopeNotNil applies the NotNil predicate on the "scope" field.
func ScopeNotNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotNull(FieldScope))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContainsFold(FieldScope, v))
}

// HandbookIsNil applies the IsNil predicate on the "handbook" field.
func HandbookIsNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIsNull(FieldHandbook))
}

// HandbookNotNil applies the NotNil predicate on the "handbook" field.
func HandbookNotNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotNull(FieldHandbook))
}

// PlaybooksIsNil applies the IsNil predicate on the "playbooks" field.
func PlaybooksIsNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIsNull(FieldPlaybooks))
}

// PlaybooksNotNil applies the NotNil predicate on the "playbooks" field.
func PlaybooksNotNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotNull(FieldPlaybooks))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotNull(FieldTags))
}

// InstallCountEQ applies the EQ predicate on the "install_count" field.
func InstallCountEQ(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldInstallCount, v))
}

// InstallCountNEQ applies the NEQ predicate on the "install_count" field.
func InstallCountNEQ(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldInstallCount, v))
}

// InstallCountIn applies the In predicate on the "install_count" field.
func InstallCountIn(vs ...int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldInstallCount, vs...))
}

// InstallCountNotIn applies the NotIn predicate on the "install_count" field.
func InstallCountNotIn(vs ...int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldInstallCount, vs...))
}

// InstallCountGT applies the GT predicate on the "install_count" field.
func InstallCountGT(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldInstallCount, v))
}

// InstallCountGTE applies the GTE predicate on the "install_count" field.
func InstallCountGTE(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldInstallCount, v))
}

// InstallCountLT applies the LT predicate on the "install_count" field.
func InstallCountLT(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldInstallCount, v))
}

// InstallCountLTE applies the LTE predicate on the "install_count" field.
func InstallCountLTE(v int) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldInstallCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.FieldContainsFold(FieldStatus, v))
}

// HasReviews applies the HasEdge predicate on the "reviews" edge.
func HasReviews() predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReviewsTable, ReviewsColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubCommunityReview
		step.Edge.Schema = schemaConfig.HubCommunityReview
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewsWith applies the HasEdge predicate on the "reviews" edge with a given conditions (other predicates).
func HasReviewsWith(preds ...predicate.HubCommunityReview) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(func(s *sql.Selector) {
		step := newReviewsStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubCommunityReview
		step.Edge.Schema = schemaConfig.HubCommunityReview
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HubCommunityWorker) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HubCommunityWorker) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HubCommunityWorker) predicate.HubCommunityWorker {
	return predicate.HubCommunityWorker(sql.NotPredicates(p))
}
