// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HubBusinessesColumns holds the columns for the "hub_businesses" table.
	HubBusinessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "repo_url", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "owner_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
	}
	// HubBusinessesTable holds the schema information for the "hub_businesses" table.
	HubBusinessesTable = &schema.Table{
		Name:       "hub_businesses",
		Columns:    HubBusinessesColumns,
		PrimaryKey: []*schema.Column{HubBusinessesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hubbusiness_status",
				Unique:  false,
				Columns: []*schema.Column{HubBusinessesColumns[8]},
			},
		},
	}
	// HubCommunityReviewsColumns holds the columns for the "hub_community_reviews" table.
	HubCommunityReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "rating", Type: field.TypeInt},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "worker_id", Type: field.TypeInt64},
	}
	// HubCommunityReviewsTable holds the schema information for the "hub_community_reviews" table.
	HubCommunityReviewsTable = &schema.Table{
		Name:       "hub_community_reviews",
		Columns:    HubCommunityReviewsColumns,
		PrimaryKey: []*schema.Column{HubCommunityReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hub_community_reviews_hub_community_workers_reviews",
				Columns:    []*schema.Column{HubCommunityReviewsColumns[6]},
				RefColumns: []*schema.Column{HubCommunityWorkersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// HubCommunityWorkersColumns holds the columns for the "hub_community_workers" table.
	HubCommunityWorkersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "publisher_user_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "domain", Type: field.TypeString, Size: 32},
		{Name: "scope", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "handbook", Type: field.TypeJSON, Nullable: true},
		{Name: "playbooks", Type: field.TypeJSON, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "install_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "published"},
	}
	// HubCommunityWorkersTable holds the schema information for the "hub_community_workers" table.
	HubCommunityWorkersTable = &schema.Table{
		Name:       "hub_community_workers",
		Columns:    HubCommunityWorkersColumns,
		PrimaryKey: []*schema.Column{HubCommunityWorkersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hubcommunityworker_domain",
				Unique:  false,
				Columns: []*schema.Column{HubCommunityWorkersColumns[6]},
			},
			{
				Name:    "hubcommunityworker_install_count",
				Unique:  false,
				Columns: []*schema.Column{HubCommunityWorkersColumns[11]},
			},
			{
				Name:    "hubcommunityworker_publisher_user_id",
				Unique:  false,
				Columns: []*schema.Column{HubCommunityWorkersColumns[3]},
			},
		},
	}
	// HubEventsColumns holds the columns for the "hub_events" table.
	HubEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "actor", Type: field.TypeString, Size: 128},
		{Name: "event_type", Type: field.TypeString, Size: 64},
		{Name: "payload", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "business_id", Type: field.TypeInt64},
	}
	// HubEventsTable holds the schema information for the "hub_events" table.
	HubEventsTable = &schema.Table{
		Name:       "hub_events",
		Columns:    HubEventsColumns,
		PrimaryKey: []*schema.Column{HubEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hub_events_hub_businesses_events",
				Columns:    []*schema.Column{HubEventsColumns[6]},
				RefColumns: []*schema.Column{HubBusinessesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "hubevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{HubEventsColumns[4]},
			},
			{
				Name:    "hubevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{HubEventsColumns[1]},
			},
			{
				Name:    "hubevent_business_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{HubEventsColumns[6], HubEventsColumns[1]},
			},
		},
	}
	// HubLocksColumns holds the columns for the "hub_locks" table.
	HubLocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "resource_key", Type: field.TypeString, Size: 256},
		{Name: "holder_token", Type: field.TypeString, Size: 64},
		{Name: "holder_worker_id", Type: field.TypeString, Size: 128},
		{Name: "acquired_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "heartbeat_at", Type: field.TypeTime},
		{Name: "released_at", Type: field.TypeTime, Nullable: true},
		{Name: "business_id", Type: field.TypeInt64},
	}
	// HubLocksTable holds the schema information for the "hub_locks" table.
	HubLocksTable = &schema.Table{
		Name:       "hub_locks",
		Columns:    HubLocksColumns,
		PrimaryKey: []*schema.Column{HubLocksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hub_locks_hub_businesses_locks",
				Columns:    []*schema.Column{HubLocksColumns[10]},
				RefColumns: []*schema.Column{HubBusinessesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// HubPlaybooksColumns holds the columns for the "hub_playbooks" table.
	HubPlaybooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "category", Type: field.TypeString, Size: 32},
		{Name: "title", Type: field.TypeString, Size: 256},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "tsv", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "created_by_worker_id", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "business_id", Type: field.TypeInt64, Nullable: true},
	}
	// HubPlaybooksTable holds the schema information for the "hub_playbooks" table.
	HubPlaybooksTable = &schema.Table{
		Name:       "hub_playbooks",
		Columns:    HubPlaybooksColumns,
		PrimaryKey: []*schema.Column{HubPlaybooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hub_playbooks_hub_businesses_playbooks",
				Columns:    []*schema.Column{HubPlaybooksColumns[10]},
				RefColumns: []*schema.Column{HubBusinessesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "hubplaybook_category",
				Unique:  false,
				Columns: []*schema.Column{HubPlaybooksColumns[4]},
			},
		},
	}
	// HubWorkersColumns holds the columns for the "hub_workers" table.
	HubWorkersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "worker_id", Type: field.TypeString, Size: 128},
		{Name: "version", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "last_heartbeat_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "offline"},
		{Name: "host", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "pid", Type: field.TypeInt, Nullable: true},
		{Name: "owner", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "handbook", Type: field.TypeJSON, Nullable: true},
		{Name: "business_id", Type: field.TypeInt64},
	}
	// HubWorkersTable holds the schema information for the "hub_workers" table.
	HubWorkersTable = &schema.Table{
		Name:       "hub_workers",
		Columns:    HubWorkersColumns,
		PrimaryKey: []*schema.Column{HubWorkersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hub_workers_hub_businesses_workers",
				Columns:    []*schema.Column{HubWorkersColumns[11]},
				RefColumns: []*schema.Column{HubBusinessesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "hubworker_business_id_worker_id",
				Unique:  true,
				Columns: []*schema.Column{HubWorkersColumns[11], HubWorkersColumns[3]},
			},
			{
				Name:    "hubworker_status",
				Unique:  false,
				Columns: []*schema.Column{HubWorkersColumns[6]},
			},
			{
				Name:    "hubworker_last_heartbeat_at",
				Unique:  false,
				Columns: []*schema.Column{HubWorkersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HubBusinessesTable,
		HubCommunityReviewsTable,
		HubCommunityWorkersTable,
		HubEventsTable,
		HubLocksTable,
		HubPlaybooksTable,
		HubWorkersTable,
	}
)

func init() {
	HubBusinessesTable.Annotation = &entsql.Annotation{
		Table: "hub_businesses",
	}
	HubCommunityReviewsTable.ForeignKeys[0].RefTable = HubCommunityWorkersTable
	HubCommunityReviewsTable.Annotation = &entsql.Annotation{
		Table: "hub_community_reviews",
	}
	HubCommunityWorkersTable.Annotation = &entsql.Annotation{
		Table: "hub_community_workers",
	}
	HubEventsTable.ForeignKeys[0].RefTable = HubBusinessesTable
	HubEventsTable.Annotation = &entsql.Annotation{
		Table: "hub_events",
	}
	HubLocksTable.ForeignKeys[0].RefTable = HubBusinessesTable
	HubLocksTable.Annotation = &entsql.Annotation{
		Table: "hub_locks",
	}
	HubPlaybooksTable.ForeignKeys[0].RefTable = HubBusinessesTable
	HubPlaybooksTable.Annotation = &entsql.Annotation{
		Table: "hub_playbooks",
	}
	HubWorkersTable.ForeignKeys[0].RefTable = HubBusinessesTable
	HubWorkersTable.Annotation = &entsql.Annotation{
		Table: "hub_workers",
	}
}
