// Code generated by ent, DO NOT EDIT.

package hubworker

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldUpdatedAt, v))
}

// BusinessID applies equality check predicate on the "business_id" field. It's identical to BusinessIDEQ.
func BusinessID(v int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldBusinessID, v))
}

// WorkerID applies equality check predicate on the "worker_id" field. It's identical to WorkerIDEQ.
func WorkerID(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldWorkerID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldVersion, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldStatus, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldHost, v))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldPid, v))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldOwner, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldUpdatedAt, v))
}

// BusinessIDEQ applies the EQ predicate on the "business_id" field.
func BusinessIDEQ(v int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldBusinessID, v))
}

// BusinessIDNEQ applies the NEQ predicate on the "business_id" field.
func BusinessIDNEQ(v int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldBusinessID, v))
}

// BusinessIDIn applies the In predicate on the "business_id" field.
func BusinessIDIn(vs ...int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldBusinessID, vs...))
}

// BusinessIDNotIn applies the NotIn predicate on the "business_id" field.
func BusinessIDNotIn(vs ...int64) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldBusinessID, vs...))
}

// WorkerIDEQ applies the EQ predicate on the "worker_id" field.
func WorkerIDEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldWorkerID, v))
}

// WorkerIDNEQ applies the NEQ predicate on the "worker_id" field.
func WorkerIDNEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldWorkerID, v))
}

// WorkerIDIn applies the In predicate on the "worker_id" field.
func WorkerIDIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldWorkerID, vs...))
}

// WorkerIDNotIn applies the NotIn predicate on the "worker_id" field.
func WorkerIDNotIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldWorkerID, vs...))
}

// WorkerIDGT applies the GT predicate on the "worker_id" field.
func WorkerIDGT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldWorkerID, v))
}

// WorkerIDGTE applies the GTE predicate on the "worker_id" field.
func WorkerIDGTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldWorkerID, v))
}

// WorkerIDLT applies the LT predicate on the "worker_id" field.
func WorkerIDLT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldWorkerID, v))
}

// WorkerIDLTE applies the LTE predicate on the "worker_id" field.
func WorkerIDLTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldWorkerID, v))
}

// WorkerIDContains applies the Contains predicate on the "worker_id" field.
func WorkerIDContains(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContains(FieldWorkerID, v))
}

// WorkerIDHasPrefix applies the HasPrefix predicate on the "worker_id" field.
func WorkerIDHasPrefix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasPrefix(FieldWorkerID, v))
}

// WorkerIDHasSuffix applies the HasSuffix predicate on the "worker_id" field.
func WorkerIDHasSuffix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasSuffix(FieldWorkerID, v))
}

// WorkerIDEqualFold applies the EqualFold predicate on the "worker_id" field.
func WorkerIDEqualFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEqualFold(FieldWorkerID, v))
}

// WorkerIDContainsFold applies the ContainsFold predicate on the "worker_id" field.
func WorkerIDContainsFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContainsFold(FieldWorkerID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionIsNil applies the IsNil predicate on the "version" field.
func VersionIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldVersion))
}

// VersionNotNil applies the NotNil predicate on the "version" field.
func VersionNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldVersion))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContainsFold(FieldVersion, v))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIsNil applies the IsNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldLastHeartbeatAt))
}

// LastHeartbeatAtNotNil applies the NotNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldLastHeartbeatAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContainsFold(FieldStatus, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasSuffix(FieldHost, v))
}

// HostIsNil applies the IsNil predicate on the "host" field.
func HostIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldHost))
}

// HostNotNil applies the NotNil predicate on the "host" field.
func HostNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldHost))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContainsFold(FieldHost, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v int) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldPid, v))
}

// PidIsNil applies the IsNil predicate on the "pid" field.
func PidIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldPid))
}

// PidNotNil applies the NotNil predicate on the "pid" field.
func PidNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldPid))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerIsNil applies the IsNil predicate on the "owner" field.
func OwnerIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldOwner))
}

// OwnerNotNil applies the NotNil predicate on the "owner" field.
func OwnerNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldOwner))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.HubWorker {
	return predicate.HubWorker(sql.FieldContainsFold(FieldOwner, v))
}

// HandbookIsNil applies the IsNil predicate on the "handbook" field.
func HandbookIsNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldIsNull(FieldHandbook))
}

// HandbookNotNil applies the NotNil predicate on the "handbook" field.
func HandbookNotNil() predicate.HubWorker {
	return predicate.HubWorker(sql.FieldNotNull(FieldHandbook))
}

// HasBusiness applies the HasEdge predicate on the "business" edge.
func HasBusiness() predicate.HubWorker {
	return predicate.HubWorker(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BusinessTable, BusinessColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubBusiness
		step.Edge.Schema = schemaConfig.HubWorker
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBusinessWith applies the HasEdge predicate on the "business" edge with a given conditions (other predicates).
func HasBusinessWith(preds ...predicate.HubBusiness) predicate.HubWorker {
	return predicate.HubWorker(func(s *sql.Selector) {
		step := newBusinessStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubBusiness
		step.Edge.Schema = schemaConfig.HubWorker
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HubWorker) predicate.HubWorker {
	return predicate.HubWorker(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HubWorker) predicate.HubWorker {
	return predicate.HubWorker(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HubWorker) predicate.HubWorker {
	return predicate.HubWorker(sql.NotPredicates(p))
}
