// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubevent"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/hubplaybook"
	"github.com/stifer/agent-hub/ent/hubworker"
)

// HubBusinessCreate is the builder for creating a HubBusiness entity.
type HubBusinessCreate struct {
	config
	mutation *HubBusinessMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HubBusinessCreate) SetCreatedAt(v time.Time) *HubBusinessCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableCreatedAt(v *time.Time) *HubBusinessCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HubBusinessCreate) SetUpdatedAt(v time.Time) *HubBusinessCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableUpdatedAt(v *time.Time) *HubBusinessCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *HubBusinessCreate) SetCode(v string) *HubBusinessCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *HubBusinessCreate) SetName(v string) *HubBusinessCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRepoURL sets the "repo_url" field.
func (_c *HubBusinessCreate) SetRepoURL(v string) *HubBusinessCreate {
	_c.mutation.SetRepoURL(v)
	return _c
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableRepoURL(v *string) *HubBusinessCreate {
	if v != nil {
		_c.SetRepoURL(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *HubBusinessCreate) SetOwnerUserID(v int64) *HubBusinessCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableOwnerUserID(v *int64) *HubBusinessCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *HubBusinessCreate) SetDescription(v string) *HubBusinessCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableDescription(v *string) *HubBusinessCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *HubBusinessCreate) SetStatus(v string) *HubBusinessCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *HubBusinessCreate) SetNillableStatus(v *string) *HubBusinessCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddWorkerIDs adds the "workers" edge to the HubWorker entity by IDs.
func (_c *HubBusinessCreate) AddWorkerIDs(ids ...int64) *HubBusinessCreate {
	_c.mutation.AddWorkerIDs(ids...)
	return _c
}

// AddWorkers adds the "workers" edges to the HubWorker entity.
func (_c *HubBusinessCreate) AddWorkers(v ...*HubWorker) *HubBusinessCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWorkerIDs(ids...)
}

// AddLockIDs adds the "locks" edge to the HubLock entity by IDs.
func (_c *HubBusinessCreate) AddLockIDs(ids ...int64) *HubBusinessCreate {
	_c.mutation.AddLockIDs(ids...)
	return _c
}

// AddLocks adds the "locks" edges to the HubLock entity.
func (_c *HubBusinessCreate) AddLocks(v ...*HubLock) *HubBusinessCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLockIDs(ids...)
}

// AddPlaybookIDs adds the "playbooks" edge to the HubPlaybook entity by IDs.
func (_c *HubBusinessCreate) AddPlaybookIDs(ids ...int64) *HubBusinessCreate {
	_c.mutation.AddPlaybookIDs(ids...)
	return _c
}

// AddPlaybooks adds the "playbooks" edges to the HubPlaybook entity.
func (_c *HubBusinessCreate) AddPlaybooks(v ...*HubPlaybook) *HubBusinessCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlaybookIDs(ids...)
}

// AddEventIDs adds the "events" edge to the HubEvent entity by IDs.
func (_c *HubBusinessCreate) AddEventIDs(ids ...int64) *HubBusinessCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the HubEvent entity.
func (_c *HubBusinessCreate) AddEvents(v ...*HubEvent) *HubBusinessCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the HubBusinessMutation object of the builder.
func (_c *HubBusinessCreate) Mutation() *HubBusinessMutation {
	return _c.mutation
}

// Save creates the HubBusiness in the database.
func (_c *HubBusinessCreate) Save(ctx context.Context) (*HubBusiness, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HubBusinessCreate) SaveX(ctx context.Context) *HubBusiness {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubBusinessCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubBusinessCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HubBusinessCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hubbusiness.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := hubbusiness.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := hubbusiness.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HubBusinessCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HubBusiness.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HubBusiness.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "HubBusiness.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := hubbusiness.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "HubBusiness.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := hubbusiness.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RepoURL(); ok {
		if err := hubbusiness.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.repo_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := hubbusiness.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HubBusiness.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := hubbusiness.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.status": %w`, err)}
		}
	}
	return nil
}

func (_c *HubBusinessCreate) sqlSave(ctx context.Context) (*HubBusiness, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HubBusinessCreate) createSpec() (*HubBusiness, *sqlgraph.CreateSpec) {
	var (
		_node = &HubBusiness{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hubbusiness.Table, sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64))
	)
	_spec.Schema = _c.schemaConfig.HubBusiness
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hubbusiness.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hubbusiness.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(hubbusiness.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(hubbusiness.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RepoURL(); ok {
		_spec.SetField(hubbusiness.FieldRepoURL, field.TypeString, value)
		_node.RepoURL = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(hubbusiness.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(hubbusiness.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(hubbusiness.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.WorkersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubLock
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlaybooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubPlaybook
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubEvent
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubBusiness.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubBusinessUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubBusinessCreate) OnConflict(opts ...sql.ConflictOption) *HubBusinessUpsertOne {
	_c.conflict = opts
	return &HubBusinessUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubBusinessCreate) OnConflictColumns(columns ...string) *HubBusinessUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubBusinessUpsertOne{
		create: _c,
	}
}

type (
	// HubBusinessUpsertOne is the builder for "upsert"-ing
	//  one HubBusiness node.
	HubBusinessUpsertOne struct {
		create *HubBusinessCreate
	}

	// HubBusinessUpsert is the "OnConflict" setter.
	HubBusinessUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HubBusinessUpsert) SetUpdatedAt(v time.Time) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateUpdatedAt() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *HubBusinessUpsert) SetCode(v string) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateCode() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *HubBusinessUpsert) SetName(v string) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateName() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldName)
	return u
}

// SetRepoURL sets the "repo_url" field.
func (u *HubBusinessUpsert) SetRepoURL(v string) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldRepoURL, v)
	return u
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateRepoURL() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldRepoURL)
	return u
}

// ClearRepoURL clears the value of the "repo_url" field.
func (u *HubBusinessUpsert) ClearRepoURL() *HubBusinessUpsert {
	u.SetNull(hubbusiness.FieldRepoURL)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *HubBusinessUpsert) SetOwnerUserID(v int64) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateOwnerUserID() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *HubBusinessUpsert) AddOwnerUserID(v int64) *HubBusinessUpsert {
	u.Add(hubbusiness.FieldOwnerUserID, v)
	return u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *HubBusinessUpsert) ClearOwnerUserID() *HubBusinessUpsert {
	u.SetNull(hubbusiness.FieldOwnerUserID)
	return u
}

// SetDescription sets the "description" field.
func (u *HubBusinessUpsert) SetDescription(v string) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateDescription() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *HubBusinessUpsert) ClearDescription() *HubBusinessUpsert {
	u.SetNull(hubbusiness.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *HubBusinessUpsert) SetStatus(v string) *HubBusinessUpsert {
	u.Set(hubbusiness.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubBusinessUpsert) UpdateStatus() *HubBusinessUpsert {
	u.SetExcluded(hubbusiness.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubBusinessUpsertOne) UpdateNewValues() *HubBusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hubbusiness.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HubBusinessUpsertOne) Ignore() *HubBusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubBusinessUpsertOne) DoNothing() *HubBusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubBusinessCreate.OnConflict
// documentation for more info.
func (u *HubBusinessUpsertOne) Update(set func(*HubBusinessUpsert)) *HubBusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubBusinessUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubBusinessUpsertOne) SetUpdatedAt(v time.Time) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateUpdatedAt() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *HubBusinessUpsertOne) SetCode(v string) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateCode() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *HubBusinessUpsertOne) SetName(v string) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateName() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateName()
	})
}

// SetRepoURL sets the "repo_url" field.
func (u *HubBusinessUpsertOne) SetRepoURL(v string) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetRepoURL(v)
	})
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateRepoURL() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateRepoURL()
	})
}

// ClearRepoURL clears the value of the "repo_url" field.
func (u *HubBusinessUpsertOne) ClearRepoURL() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearRepoURL()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *HubBusinessUpsertOne) SetOwnerUserID(v int64) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *HubBusinessUpsertOne) AddOwnerUserID(v int64) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateOwnerUserID() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *HubBusinessUpsertOne) ClearOwnerUserID() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetDescription sets the "description" field.
func (u *HubBusinessUpsertOne) SetDescription(v string) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateDescription() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HubBusinessUpsertOne) ClearDescription() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *HubBusinessUpsertOne) SetStatus(v string) *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubBusinessUpsertOne) UpdateStatus() *HubBusinessUpsertOne {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *HubBusinessUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubBusinessCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubBusinessUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HubBusinessUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HubBusinessUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HubBusinessCreateBulk is the builder for creating many HubBusiness entities in bulk.
type HubBusinessCreateBulk struct {
	config
	err      error
	builders []*HubBusinessCreate
	conflict []sql.ConflictOption
}

// Save creates the HubBusiness entities in the database.
func (_c *HubBusinessCreateBulk) Save(ctx context.Context) ([]*HubBusiness, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HubBusiness, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HubBusinessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HubBusinessCreateBulk) SaveX(ctx context.Context) []*HubBusiness {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubBusinessCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubBusinessCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubBusiness.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubBusinessUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubBusinessCreateBulk) OnConflict(opts ...sql.ConflictOption) *HubBusinessUpsertBulk {
	_c.conflict = opts
	return &HubBusinessUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubBusinessCreateBulk) OnConflictColumns(columns ...string) *HubBusinessUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubBusinessUpsertBulk{
		create: _c,
	}
}

// HubBusinessUpsertBulk is the builder for "upsert"-ing
// a bulk of HubBusiness nodes.
type HubBusinessUpsertBulk struct {
	create *HubBusinessCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubBusinessUpsertBulk) UpdateNewValues() *HubBusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hubbusiness.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubBusiness.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HubBusinessUpsertBulk) Ignore() *HubBusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubBusinessUpsertBulk) DoNothing() *HubBusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubBusinessCreateBulk.OnConflict
// documentation for more info.
func (u *HubBusinessUpsertBulk) Update(set func(*HubBusinessUpsert)) *HubBusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubBusinessUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubBusinessUpsertBulk) SetUpdatedAt(v time.Time) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateUpdatedAt() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *HubBusinessUpsertBulk) SetCode(v string) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateCode() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *HubBusinessUpsertBulk) SetName(v string) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateName() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateName()
	})
}

// SetRepoURL sets the "repo_url" field.
func (u *HubBusinessUpsertBulk) SetRepoURL(v string) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetRepoURL(v)
	})
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateRepoURL() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateRepoURL()
	})
}

// ClearRepoURL clears the value of the "repo_url" field.
func (u *HubBusinessUpsertBulk) ClearRepoURL() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearRepoURL()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *HubBusinessUpsertBulk) SetOwnerUserID(v int64) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *HubBusinessUpsertBulk) AddOwnerUserID(v int64) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateOwnerUserID() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *HubBusinessUpsertBulk) ClearOwnerUserID() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetDescription sets the "description" field.
func (u *HubBusinessUpsertBulk) SetDescription(v string) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateDescription() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HubBusinessUpsertBulk) ClearDescription() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *HubBusinessUpsertBulk) SetStatus(v string) *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubBusinessUpsertBulk) UpdateStatus() *HubBusinessUpsertBulk {
	return u.Update(func(s *HubBusinessUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *HubBusinessUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HubBusinessCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubBusinessCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubBusinessUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
