// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubevent"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/hubplaybook"
	"github.com/stifer/agent-hub/ent/hubworker"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubBusinessQuery is the builder for querying HubBusiness entities.
type HubBusinessQuery struct {
	config
	ctx           *QueryContext
	order         []hubbusiness.OrderOption
	inters        []Interceptor
	predicates    []predicate.HubBusiness
	withWorkers   *HubWorkerQuery
	withLocks     *HubLockQuery
	withPlaybooks *HubPlaybookQuery
	withEvents    *HubEventQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HubBusinessQuery builder.
func (_q *HubBusinessQuery) Where(ps ...predicate.HubBusiness) *HubBusinessQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HubBusinessQuery) Limit(limit int) *HubBusinessQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HubBusinessQuery) Offset(offset int) *HubBusinessQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HubBusinessQuery) Unique(unique bool) *HubBusinessQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HubBusinessQuery) Order(o ...hubbusiness.OrderOption) *HubBusinessQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWorkers chains the current query on the "workers" edge.
func (_q *HubBusinessQuery) QueryWorkers() *HubWorkerQuery {
	query := (&HubWorkerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hubbusiness.Table, hubbusiness.FieldID, selector),
			sqlgraph.To(hubworker.Table, hubworker.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, hubbusiness.WorkersTable, hubbusiness.WorkersColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.HubWorker
		step.Edge.Schema = schemaConfig.HubWorker
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocks chains the current query on the "locks" edge.
func (_q *HubBusinessQuery) QueryLocks() *HubLockQuery {
	query := (&HubLockClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hubbusiness.Table, hubbusiness.FieldID, selector),
			sqlgraph.To(hublock.Table, hublock.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, hubbusiness.LocksTable, hubbusiness.LocksColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.HubLock
		step.Edge.Schema = schemaConfig.HubLock
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlaybooks chains the current query on the "playbooks" edge.
func (_q *HubBusinessQuery) QueryPlaybooks() *HubPlaybookQuery {
	query := (&HubPlaybookClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hubbusiness.Table, hubbusiness.FieldID, selector),
			sqlgraph.To(hubplaybook.Table, hubplaybook.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, hubbusiness.PlaybooksTable, hubbusiness.PlaybooksColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.HubPlaybook
		step.Edge.Schema = schemaConfig.HubPlaybook
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *HubBusinessQuery) QueryEvents() *HubEventQuery {
	query := (&HubEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hubbusiness.Table, hubbusiness.FieldID, selector),
			sqlgraph.To(hubevent.Table, hubevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, hubbusiness.EventsTable, hubbusiness.EventsColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.HubEvent
		step.Edge.Schema = schemaConfig.HubEvent
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HubBusiness entity from the query.
// Returns a *NotFoundError when no HubBusiness was found.
func (_q *HubBusinessQuery) First(ctx context.Context) (*HubBusiness, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hubbusiness.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HubBusinessQuery) FirstX(ctx context.Context) *HubBusiness {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HubBusiness ID from the query.
// Returns a *NotFoundError when no HubBusiness ID was found.
func (_q *HubBusinessQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hubbusiness.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HubBusinessQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HubBusiness entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HubBusiness entity is found.
// Returns a *NotFoundError when no HubBusiness entities are found.
func (_q *HubBusinessQuery) Only(ctx context.Context) (*HubBusiness, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hubbusiness.Label}
	default:
		return nil, &NotSingularError{hubbusiness.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HubBusinessQuery) OnlyX(ctx context.Context) *HubBusiness {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HubBusiness ID in the query.
// Returns a *NotSingularError when more than one HubBusiness ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HubBusinessQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hubbusiness.Label}
	default:
		err = &NotSingularError{hubbusiness.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HubBusinessQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HubBusinesses.
func (_q *HubBusinessQuery) All(ctx context.Context) ([]*HubBusiness, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HubBusiness, *HubBusinessQuery]()
	return withInterceptors[[]*HubBusiness](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HubBusinessQuery) AllX(ctx context.Context) []*HubBusiness {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HubBusiness IDs.
func (_q *HubBusinessQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(hubbusiness.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HubBusinessQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HubBusinessQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HubBusinessQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HubBusinessQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HubBusinessQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HubBusinessQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HubBusinessQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HubBusinessQuery) Clone() *HubBusinessQuery {
	if _q == nil {
		return nil
	}
	return &HubBusinessQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]hubbusiness.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.HubBusiness{}, _q.predicates...),
		withWorkers:   _q.withWorkers.Clone(),
		withLocks:     _q.withLocks.Clone(),
		withPlaybooks: _q.withPlaybooks.Clone(),
		withEvents:    _q.withEvents.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWorkers tells the query-builder to eager-load the nodes that are connected to
// the "workers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HubBusinessQuery) WithWorkers(opts ...func(*HubWorkerQuery)) *HubBusinessQuery {
	query := (&HubWorkerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkers = query
	return _q
}

// WithLocks tells the query-builder to eager-load the nodes that are connected to
// the "locks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HubBusinessQuery) WithLocks(opts ...func(*HubLockQuery)) *HubBusinessQuery {
	query := (&HubLockClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocks = query
	return _q
}

// WithPlaybooks tells the query-builder to eager-load the nodes that are connected to
// the "playbooks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HubBusinessQuery) WithPlaybooks(opts ...func(*HubPlaybookQuery)) *HubBusinessQuery {
	query := (&HubPlaybookClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlaybooks = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HubBusinessQuery) WithEvents(opts ...func(*HubEventQuery)) *HubBusinessQuery {
	query := (&HubEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HubBusiness.Query().
//		GroupBy(hubbusiness.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HubBusinessQuery) GroupBy(field string, fields ...string) *HubBusinessGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HubBusinessGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = hubbusiness.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.HubBusiness.Query().
//		Select(hubbusiness.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *HubBusinessQuery) Select(fields ...string) *HubBusinessSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HubBusinessSelect{HubBusinessQuery: _q}
	sbuild.label = hubbusiness.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HubBusinessSelect configured with the given aggregations.
func (_q *HubBusinessQuery) Aggregate(fns ...AggregateFunc) *HubBusinessSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HubBusinessQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !hubbusiness.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *HubBusinessQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HubBusiness, error) {
	var (
		nodes       = []*HubBusiness{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withWorkers != nil,
			_q.withLocks != nil,
			_q.withPlaybooks != nil,
			_q.withEvents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HubBusiness).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HubBusiness{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.HubBusiness
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWorkers; query != nil {
		if err := _q.loadWorkers(ctx, query, nodes,
			func(n *HubBusiness) { n.Edges.Workers = []*HubWorker{} },
			func(n *HubBusiness, e *HubWorker) { n.Edges.Workers = append(n.Edges.Workers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocks; query != nil {
		if err := _q.loadLocks(ctx, query, nodes,
			func(n *HubBusiness) { n.Edges.Locks = []*HubLock{} },
			func(n *HubBusiness, e *HubLock) { n.Edges.Locks = append(n.Edges.Locks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlaybooks; query != nil {
		if err := _q.loadPlaybooks(ctx, query, nodes,
			func(n *HubBusiness) { n.Edges.Playbooks = []*HubPlaybook{} },
			func(n *HubBusiness, e *HubPlaybook) { n.Edges.Playbooks = append(n.Edges.Playbooks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *HubBusiness) { n.Edges.Events = []*HubEvent{} },
			func(n *HubBusiness, e *HubEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HubBusinessQuery) loadWorkers(ctx context.Context, query *HubWorkerQuery, nodes []*HubBusiness, init func(*HubBusiness), assign func(*HubBusiness, *HubWorker)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*HubBusiness)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hubworker.FieldBusinessID)
	}
	query.Where(predicate.HubWorker(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hubbusiness.WorkersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HubBusinessQuery) loadLocks(ctx context.Context, query *HubLockQuery, nodes []*HubBusiness, init func(*HubBusiness), assign func(*HubBusiness, *HubLock)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*HubBusiness)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hublock.FieldBusinessID)
	}
	query.Where(predicate.HubLock(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hubbusiness.LocksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HubBusinessQuery) loadPlaybooks(ctx context.Context, query *HubPlaybookQuery, nodes []*HubBusiness, init func(*HubBusiness), assign func(*HubBusiness, *HubPlaybook)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*HubBusiness)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hubplaybook.FieldBusinessID)
	}
	query.Where(predicate.HubPlaybook(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hubbusiness.PlaybooksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HubBusinessQuery) loadEvents(ctx context.Context, query *HubEventQuery, nodes []*HubBusiness, init func(*HubBusiness), assign func(*HubBusiness, *HubEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*HubBusiness)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hubevent.FieldBusinessID)
	}
	query.Where(predicate.HubEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hubbusiness.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *HubBusinessQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.HubBusiness
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HubBusinessQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hubbusiness.Table, hubbusiness.Columns, sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hubbusiness.FieldID)
		for i := range fields {
			if fields[i] != hubbusiness.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HubBusinessQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(hubbusiness.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = hubbusiness.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.HubBusiness)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HubBusinessGroupBy is the group-by builder for HubBusiness entities.
type HubBusinessGroupBy struct {
	selector
	build *HubBusinessQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HubBusinessGroupBy) Aggregate(fns ...AggregateFunc) *HubBusinessGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HubBusinessGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HubBusinessQuery, *HubBusinessGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HubBusinessGroupBy) sqlScan(ctx context.Context, root *HubBusinessQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HubBusinessSelect is the builder for selecting fields of HubBusiness entities.
type HubBusinessSelect struct {
	*HubBusinessQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HubBusinessSelect) Aggregate(fns ...AggregateFunc) *HubBusinessSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HubBusinessSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HubBusinessQuery, *HubBusinessSelect](ctx, _s.HubBusinessQuery, _s, _s.inters, v)
}

func (_s *HubBusinessSelect) sqlScan(ctx context.Context, root *HubBusinessQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
