// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubBusinessDelete is the builder for deleting a HubBusiness entity.
type HubBusinessDelete struct {
	config
	hooks    []Hook
	mutation *HubBusinessMutation
}

// Where appends a list predicates to the HubBusinessDelete builder.
func (_d *HubBusinessDelete) Where(ps ...predicate.HubBusiness) *HubBusinessDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HubBusinessDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubBusinessDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HubBusinessDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hubbusiness.Table, sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64))
	_spec.Node.Schema = _d.schemaConfig.HubBusiness
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HubBusinessDeleteOne is the builder for deleting a single HubBusiness entity.
type HubBusinessDeleteOne struct {
	_d *HubBusinessDelete
}

// Where appends a list predicates to the HubBusinessDelete builder.
func (_d *HubBusinessDeleteOne) Where(ps ...predicate.HubBusiness) *HubBusinessDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HubBusinessDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hubbusiness.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubBusinessDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
