// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubevent"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/hubplaybook"
	"github.com/stifer/agent-hub/ent/hubworker"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubBusinessUpdate is the builder for updating HubBusiness entities.
type HubBusinessUpdate struct {
	config
	hooks    []Hook
	mutation *HubBusinessMutation
}

// Where appends a list predicates to the HubBusinessUpdate builder.
func (_u *HubBusinessUpdate) Where(ps ...predicate.HubBusiness) *HubBusinessUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HubBusinessUpdate) SetUpdatedAt(v time.Time) *HubBusinessUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *HubBusinessUpdate) SetCode(v string) *HubBusinessUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableCode(v *string) *HubBusinessUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HubBusinessUpdate) SetName(v string) *HubBusinessUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableName(v *string) *HubBusinessUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *HubBusinessUpdate) SetRepoURL(v string) *HubBusinessUpdate {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableRepoURL(v *string) *HubBusinessUpdate {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// ClearRepoURL clears the value of the "repo_url" field.
func (_u *HubBusinessUpdate) ClearRepoURL() *HubBusinessUpdate {
	_u.mutation.ClearRepoURL()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *HubBusinessUpdate) SetOwnerUserID(v int64) *HubBusinessUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableOwnerUserID(v *int64) *HubBusinessUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *HubBusinessUpdate) AddOwnerUserID(v int64) *HubBusinessUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *HubBusinessUpdate) ClearOwnerUserID() *HubBusinessUpdate {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *HubBusinessUpdate) SetDescription(v string) *HubBusinessUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableDescription(v *string) *HubBusinessUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HubBusinessUpdate) ClearDescription() *HubBusinessUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HubBusinessUpdate) SetStatus(v string) *HubBusinessUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HubBusinessUpdate) SetNillableStatus(v *string) *HubBusinessUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddWorkerIDs adds the "workers" edge to the HubWorker entity by IDs.
func (_u *HubBusinessUpdate) AddWorkerIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.AddWorkerIDs(ids...)
	return _u
}

// AddWorkers adds the "workers" edges to the HubWorker entity.
func (_u *HubBusinessUpdate) AddWorkers(v ...*HubWorker) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkerIDs(ids...)
}

// AddLockIDs adds the "locks" edge to the HubLock entity by IDs.
func (_u *HubBusinessUpdate) AddLockIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.AddLockIDs(ids...)
	return _u
}

// AddLocks adds the "locks" edges to the HubLock entity.
func (_u *HubBusinessUpdate) AddLocks(v ...*HubLock) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLockIDs(ids...)
}

// AddPlaybookIDs adds the "playbooks" edge to the HubPlaybook entity by IDs.
func (_u *HubBusinessUpdate) AddPlaybookIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.AddPlaybookIDs(ids...)
	return _u
}

// AddPlaybooks adds the "playbooks" edges to the HubPlaybook entity.
func (_u *HubBusinessUpdate) AddPlaybooks(v ...*HubPlaybook) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaybookIDs(ids...)
}

// AddEventIDs adds the "events" edge to the HubEvent entity by IDs.
func (_u *HubBusinessUpdate) AddEventIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the HubEvent entity.
func (_u *HubBusinessUpdate) AddEvents(v ...*HubEvent) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the HubBusinessMutation object of the builder.
func (_u *HubBusinessUpdate) Mutation() *HubBusinessMutation {
	return _u.mutation
}

// ClearWorkers clears all "workers" edges to the HubWorker entity.
func (_u *HubBusinessUpdate) ClearWorkers() *HubBusinessUpdate {
	_u.mutation.ClearWorkers()
	return _u
}

// RemoveWorkerIDs removes the "workers" edge to HubWorker entities by IDs.
func (_u *HubBusinessUpdate) RemoveWorkerIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.RemoveWorkerIDs(ids...)
	return _u
}

// RemoveWorkers removes "workers" edges to HubWorker entities.
func (_u *HubBusinessUpdate) RemoveWorkers(v ...*HubWorker) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkerIDs(ids...)
}

// ClearLocks clears all "locks" edges to the HubLock entity.
func (_u *HubBusinessUpdate) ClearLocks() *HubBusinessUpdate {
	_u.mutation.ClearLocks()
	return _u
}

// RemoveLockIDs removes the "locks" edge to HubLock entities by IDs.
func (_u *HubBusinessUpdate) RemoveLockIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.RemoveLockIDs(ids...)
	return _u
}

// RemoveLocks removes "locks" edges to HubLock entities.
func (_u *HubBusinessUpdate) RemoveLocks(v ...*HubLock) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLockIDs(ids...)
}

// ClearPlaybooks clears all "playbooks" edges to the HubPlaybook entity.
func (_u *HubBusinessUpdate) ClearPlaybooks() *HubBusinessUpdate {
	_u.mutation.ClearPlaybooks()
	return _u
}

// RemovePlaybookIDs removes the "playbooks" edge to HubPlaybook entities by IDs.
func (_u *HubBusinessUpdate) RemovePlaybookIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.RemovePlaybookIDs(ids...)
	return _u
}

// RemovePlaybooks removes "playbooks" edges to HubPlaybook entities.
func (_u *HubBusinessUpdate) RemovePlaybooks(v ...*HubPlaybook) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaybookIDs(ids...)
}

// ClearEvents clears all "events" edges to the HubEvent entity.
func (_u *HubBusinessUpdate) ClearEvents() *HubBusinessUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to HubEvent entities by IDs.
func (_u *HubBusinessUpdate) RemoveEventIDs(ids ...int64) *HubBusinessUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to HubEvent entities.
func (_u *HubBusinessUpdate) RemoveEvents(v ...*HubEvent) *HubBusinessUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HubBusinessUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubBusinessUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HubBusinessUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubBusinessUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubBusinessUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hubbusiness.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubBusinessUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := hubbusiness.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := hubbusiness.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := hubbusiness.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.repo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := hubbusiness.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := hubbusiness.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.status": %w`, err)}
		}
	}
	return nil
}

func (_u *HubBusinessUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubbusiness.Table, hubbusiness.Columns, sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hubbusiness.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(hubbusiness.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hubbusiness.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(hubbusiness.FieldRepoURL, field.TypeString, value)
	}
	if _u.mutation.RepoURLCleared() {
		_spec.ClearField(hubbusiness.FieldRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(hubbusiness.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(hubbusiness.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(hubbusiness.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hubbusiness.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hubbusiness.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hubbusiness.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.WorkersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkersIDs(); len(nodes) > 0 && !_u.mutation.WorkersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLocksIDs(); len(nodes) > 0 && !_u.mutation.LocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaybooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaybooksIDs(); len(nodes) > 0 && !_u.mutation.PlaybooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaybooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.HubBusiness
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubbusiness.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HubBusinessUpdateOne is the builder for updating a single HubBusiness entity.
type HubBusinessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HubBusinessMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HubBusinessUpdateOne) SetUpdatedAt(v time.Time) *HubBusinessUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *HubBusinessUpdateOne) SetCode(v string) *HubBusinessUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableCode(v *string) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HubBusinessUpdateOne) SetName(v string) *HubBusinessUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableName(v *string) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *HubBusinessUpdateOne) SetRepoURL(v string) *HubBusinessUpdateOne {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableRepoURL(v *string) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// ClearRepoURL clears the value of the "repo_url" field.
func (_u *HubBusinessUpdateOne) ClearRepoURL() *HubBusinessUpdateOne {
	_u.mutation.ClearRepoURL()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *HubBusinessUpdateOne) SetOwnerUserID(v int64) *HubBusinessUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableOwnerUserID(v *int64) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *HubBusinessUpdateOne) AddOwnerUserID(v int64) *HubBusinessUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *HubBusinessUpdateOne) ClearOwnerUserID() *HubBusinessUpdateOne {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *HubBusinessUpdateOne) SetDescription(v string) *HubBusinessUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableDescription(v *string) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HubBusinessUpdateOne) ClearDescription() *HubBusinessUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HubBusinessUpdateOne) SetStatus(v string) *HubBusinessUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HubBusinessUpdateOne) SetNillableStatus(v *string) *HubBusinessUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddWorkerIDs adds the "workers" edge to the HubWorker entity by IDs.
func (_u *HubBusinessUpdateOne) AddWorkerIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.AddWorkerIDs(ids...)
	return _u
}

// AddWorkers adds the "workers" edges to the HubWorker entity.
func (_u *HubBusinessUpdateOne) AddWorkers(v ...*HubWorker) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkerIDs(ids...)
}

// AddLockIDs adds the "locks" edge to the HubLock entity by IDs.
func (_u *HubBusinessUpdateOne) AddLockIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.AddLockIDs(ids...)
	return _u
}

// AddLocks adds the "locks" edges to the HubLock entity.
func (_u *HubBusinessUpdateOne) AddLocks(v ...*HubLock) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLockIDs(ids...)
}

// AddPlaybookIDs adds the "playbooks" edge to the HubPlaybook entity by IDs.
func (_u *HubBusinessUpdateOne) AddPlaybookIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.AddPlaybookIDs(ids...)
	return _u
}

// AddPlaybooks adds the "playbooks" edges to the HubPlaybook entity.
func (_u *HubBusinessUpdateOne) AddPlaybooks(v ...*HubPlaybook) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaybookIDs(ids...)
}

// AddEventIDs adds the "events" edge to the HubEvent entity by IDs.
func (_u *HubBusinessUpdateOne) AddEventIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the HubEvent entity.
func (_u *HubBusinessUpdateOne) AddEvents(v ...*HubEvent) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the HubBusinessMutation object of the builder.
func (_u *HubBusinessUpdateOne) Mutation() *HubBusinessMutation {
	return _u.mutation
}

// ClearWorkers clears all "workers" edges to the HubWorker entity.
func (_u *HubBusinessUpdateOne) ClearWorkers() *HubBusinessUpdateOne {
	_u.mutation.ClearWorkers()
	return _u
}

// RemoveWorkerIDs removes the "workers" edge to HubWorker entities by IDs.
func (_u *HubBusinessUpdateOne) RemoveWorkerIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.RemoveWorkerIDs(ids...)
	return _u
}

// RemoveWorkers removes "workers" edges to HubWorker entities.
func (_u *HubBusinessUpdateOne) RemoveWorkers(v ...*HubWorker) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkerIDs(ids...)
}

// ClearLocks clears all "locks" edges to the HubLock entity.
func (_u *HubBusinessUpdateOne) ClearLocks() *HubBusinessUpdateOne {
	_u.mutation.ClearLocks()
	return _u
}

// RemoveLockIDs removes the "locks" edge to HubLock entities by IDs.
func (_u *HubBusinessUpdateOne) RemoveLockIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.RemoveLockIDs(ids...)
	return _u
}

// RemoveLocks removes "locks" edges to HubLock entities.
func (_u *HubBusinessUpdateOne) RemoveLocks(v ...*HubLock) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLockIDs(ids...)
}

// ClearPlaybooks clears all "playbooks" edges to the HubPlaybook entity.
func (_u *HubBusinessUpdateOne) ClearPlaybooks() *HubBusinessUpdateOne {
	_u.mutation.ClearPlaybooks()
	return _u
}

// RemovePlaybookIDs removes the "playbooks" edge to HubPlaybook entities by IDs.
func (_u *HubBusinessUpdateOne) RemovePlaybookIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.RemovePlaybookIDs(ids...)
	return _u
}

// RemovePlaybooks removes "playbooks" edges to HubPlaybook entities.
func (_u *HubBusinessUpdateOne) RemovePlaybooks(v ...*HubPlaybook) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaybookIDs(ids...)
}

// ClearEvents clears all "events" edges to the HubEvent entity.
func (_u *HubBusinessUpdateOne) ClearEvents() *HubBusinessUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to HubEvent entities by IDs.
func (_u *HubBusinessUpdateOne) RemoveEventIDs(ids ...int64) *HubBusinessUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to HubEvent entities.
func (_u *HubBusinessUpdateOne) RemoveEvents(v ...*HubEvent) *HubBusinessUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the HubBusinessUpdate builder.
func (_u *HubBusinessUpdateOne) Where(ps ...predicate.HubBusiness) *HubBusinessUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HubBusinessUpdateOne) Select(field string, fields ...string) *HubBusinessUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HubBusiness entity.
func (_u *HubBusinessUpdateOne) Save(ctx context.Context) (*HubBusiness, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubBusinessUpdateOne) SaveX(ctx context.Context) *HubBusiness {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HubBusinessUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubBusinessUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubBusinessUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hubbusiness.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubBusinessUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := hubbusiness.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := hubbusiness.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := hubbusiness.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.repo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := hubbusiness.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := hubbusiness.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubBusiness.status": %w`, err)}
		}
	}
	return nil
}

func (_u *HubBusinessUpdateOne) sqlSave(ctx context.Context) (_node *HubBusiness, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubbusiness.Table, hubbusiness.Columns, sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HubBusiness.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hubbusiness.FieldID)
		for _, f := range fields {
			if !hubbusiness.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hubbusiness.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hubbusiness.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(hubbusiness.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hubbusiness.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(hubbusiness.FieldRepoURL, field.TypeString, value)
	}
	if _u.mutation.RepoURLCleared() {
		_spec.ClearField(hubbusiness.FieldRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(hubbusiness.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(hubbusiness.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(hubbusiness.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hubbusiness.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(hubbusiness.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hubbusiness.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.WorkersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkersIDs(); len(nodes) > 0 && !_u.mutation.WorkersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.WorkersTable,
			Columns: []string{hubbusiness.WorkersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLocksIDs(); len(nodes) > 0 && !_u.mutation.LocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.LocksTable,
			Columns: []string{hubbusiness.LocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubLock
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaybooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaybooksIDs(); len(nodes) > 0 && !_u.mutation.PlaybooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaybooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.PlaybooksTable,
			Columns: []string{hubbusiness.PlaybooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubplaybook.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubPlaybook
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubbusiness.EventsTable,
			Columns: []string{hubbusiness.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubevent.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubEvent
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.HubBusiness
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &HubBusiness{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubbusiness.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
