// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubCommunityWorkerDelete is the builder for deleting a HubCommunityWorker entity.
type HubCommunityWorkerDelete struct {
	config
	hooks    []Hook
	mutation *HubCommunityWorkerMutation
}

// Where appends a list predicates to the HubCommunityWorkerDelete builder.
func (_d *HubCommunityWorkerDelete) Where(ps ...predicate.HubCommunityWorker) *HubCommunityWorkerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HubCommunityWorkerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubCommunityWorkerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HubCommunityWorkerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hubcommunityworker.Table, sqlgraph.NewFieldSpec(hubcommunityworker.FieldID, field.TypeInt64))
	_spec.Node.Schema = _d.schemaConfig.HubCommunityWorker
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HubCommunityWorkerDeleteOne is the builder for deleting a single HubCommunityWorker entity.
type HubCommunityWorkerDeleteOne struct {
	_d *HubCommunityWorkerDelete
}

// Where appends a list predicates to the HubCommunityWorkerDelete builder.
func (_d *HubCommunityWorkerDeleteOne) Where(ps ...predicate.HubCommunityWorker) *HubCommunityWorkerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HubCommunityWorkerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hubcommunityworker.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubCommunityWorkerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
