// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubCommunityReviewDelete is the builder for deleting a HubCommunityReview entity.
type HubCommunityReviewDelete struct {
	config
	hooks    []Hook
	mutation *HubCommunityReviewMutation
}

// Where appends a list predicates to the HubCommunityReviewDelete builder.
func (_d *HubCommunityReviewDelete) Where(ps ...predicate.HubCommunityReview) *HubCommunityReviewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HubCommunityReviewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubCommunityReviewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HubCommunityReviewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hubcommunityreview.Table, sqlgraph.NewFieldSpec(hubcommunityreview.FieldID, field.TypeInt64))
	_spec.Node.Schema = _d.schemaConfig.HubCommunityReview
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HubCommunityReviewDeleteOne is the builder for deleting a single HubCommunityReview entity.
type HubCommunityReviewDeleteOne struct {
	_d *HubCommunityReviewDelete
}

// Where appends a list predicates to the HubCommunityReviewDelete builder.
func (_d *HubCommunityReviewDeleteOne) Where(ps ...predicate.HubCommunityReview) *HubCommunityReviewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HubCommunityReviewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hubcommunityreview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubCommunityReviewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
