// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
)

// HubCommunityReview is the model entity for the HubCommunityReview schema.
type HubCommunityReview struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// WorkerID holds the value of the "worker_id" field.
	WorkerID int64 `json:"worker_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating int `json:"rating,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HubCommunityReviewQuery when eager-loading is set.
	Edges        HubCommunityReviewEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HubCommunityReviewEdges holds the relations/edges for other nodes in the graph.
type HubCommunityReviewEdges struct {
	// CommunityWorker holds the value of the community_worker edge.
	CommunityWorker *HubCommunityWorker `json:"community_worker,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CommunityWorkerOrErr returns the CommunityWorker value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HubCommunityReviewEdges) CommunityWorkerOrErr() (*HubCommunityWorker, error) {
	if e.CommunityWorker != nil {
		return e.CommunityWorker, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hubcommunityworker.Label}
	}
	return nil, &NotLoadedError{edge: "community_worker"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HubCommunityReview) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hubcommunityreview.FieldID, hubcommunityreview.FieldWorkerID, hubcommunityreview.FieldUserID, hubcommunityreview.FieldRating:
			values[i] = new(sql.NullInt64)
		case hubcommunityreview.FieldComment:
			values[i] = new(sql.NullString)
		case hubcommunityreview.FieldCreatedAt, hubcommunityreview.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HubCommunityReview fields.
func (_m *HubCommunityReview) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hubcommunityreview.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case hubcommunityreview.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case hubcommunityreview.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case hubcommunityreview.FieldWorkerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = value.Int64
			}
		case hubcommunityreview.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case hubcommunityreview.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int(value.Int64)
			}
		case hubcommunityreview.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HubCommunityReview.
// This includes values selected through modifiers, order, etc.
func (_m *HubCommunityReview) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCommunityWorker queries the "community_worker" edge of the HubCommunityReview entity.
func (_m *HubCommunityReview) QueryCommunityWorker() *HubCommunityWorkerQuery {
	return NewHubCommunityReviewClient(_m.config).QueryCommunityWorker(_m)
}

// Update returns a builder for updating this HubCommunityReview.
// Note that you need to call HubCommunityReview.Unwrap() before calling this method if this HubCommunityReview
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HubCommunityReview) Update() *HubCommunityReviewUpdateOne {
	return NewHubCommunityReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HubCommunityReview entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HubCommunityReview) Unwrap() *HubCommunityReview {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HubCommunityReview is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HubCommunityReview) String() string {
	var builder strings.Builder
	builder.WriteString("HubCommunityReview(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("worker_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkerID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteByte(')')
	return builder.String()
}

// HubCommunityReviews is a parsable slice of HubCommunityReview.
type HubCommunityReviews []*HubCommunityReview
