// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
)

// HubCommunityWorkerCreate is the builder for creating a HubCommunityWorker entity.
type HubCommunityWorkerCreate struct {
	config
	mutation *HubCommunityWorkerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HubCommunityWorkerCreate) SetCreatedAt(v time.Time) *HubCommunityWorkerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableCreatedAt(v *time.Time) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HubCommunityWorkerCreate) SetUpdatedAt(v time.Time) *HubCommunityWorkerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableUpdatedAt(v *time.Time) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublisherUserID sets the "publisher_user_id" field.
func (_c *HubCommunityWorkerCreate) SetPublisherUserID(v int64) *HubCommunityWorkerCreate {
	_c.mutation.SetPublisherUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *HubCommunityWorkerCreate) SetTitle(v string) *HubCommunityWorkerCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *HubCommunityWorkerCreate) SetDescription(v string) *HubCommunityWorkerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableDescription(v *string) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *HubCommunityWorkerCreate) SetDomain(v string) *HubCommunityWorkerCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *HubCommunityWorkerCreate) SetScope(v string) *HubCommunityWorkerCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableScope(v *string) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetHandbook sets the "handbook" field.
func (_c *HubCommunityWorkerCreate) SetHandbook(v map[string]interface{}) *HubCommunityWorkerCreate {
	_c.mutation.SetHandbook(v)
	return _c
}

// SetPlaybooks sets the "playbooks" field.
func (_c *HubCommunityWorkerCreate) SetPlaybooks(v map[string]interface{}) *HubCommunityWorkerCreate {
	_c.mutation.SetPlaybooks(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *HubCommunityWorkerCreate) SetTags(v []string) *HubCommunityWorkerCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetInstallCount sets the "install_count" field.
func (_c *HubCommunityWorkerCreate) SetInstallCount(v int) *HubCommunityWorkerCreate {
	_c.mutation.SetInstallCount(v)
	return _c
}

// SetNillableInstallCount sets the "install_count" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableInstallCount(v *int) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetInstallCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *HubCommunityWorkerCreate) SetStatus(v string) *HubCommunityWorkerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *HubCommunityWorkerCreate) SetNillableStatus(v *string) *HubCommunityWorkerCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddReviewIDs adds the "reviews" edge to the HubCommunityReview entity by IDs.
func (_c *HubCommunityWorkerCreate) AddReviewIDs(ids ...int64) *HubCommunityWorkerCreate {
	_c.mutation.AddReviewIDs(ids...)
	return _c
}

// AddReviews adds the "reviews" edges to the HubCommunityReview entity.
func (_c *HubCommunityWorkerCreate) AddReviews(v ...*HubCommunityReview) *HubCommunityWorkerCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewIDs(ids...)
}

// Mutation returns the HubCommunityWorkerMutation object of the builder.
func (_c *HubCommunityWorkerCreate) Mutation() *HubCommunityWorkerMutation {
	return _c.mutation
}

// Save creates the HubCommunityWorker in the database.
func (_c *HubCommunityWorkerCreate) Save(ctx context.Context) (*HubCommunityWorker, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HubCommunityWorkerCreate) SaveX(ctx context.Context) *HubCommunityWorker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubCommunityWorkerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubCommunityWorkerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HubCommunityWorkerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hubcommunityworker.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := hubcommunityworker.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.InstallCount(); !ok {
		v := hubcommunityworker.DefaultInstallCount
		_c.mutation.SetInstallCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := hubcommunityworker.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HubCommunityWorkerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HubCommunityWorker.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HubCommunityWorker.updated_at"`)}
	}
	if _, ok := _c.mutation.PublisherUserID(); !ok {
		return &ValidationError{Name: "publisher_user_id", err: errors.New(`ent: missing required field "HubCommunityWorker.publisher_user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "HubCommunityWorker.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := hubcommunityworker.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "HubCommunityWorker.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "HubCommunityWorker.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := hubcommunityworker.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "HubCommunityWorker.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstallCount(); !ok {
		return &ValidationError{Name: "install_count", err: errors.New(`ent: missing required field "HubCommunityWorker.install_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HubCommunityWorker.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := hubcommunityworker.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubCommunityWorker.status": %w`, err)}
		}
	}
	return nil
}

func (_c *HubCommunityWorkerCreate) sqlSave(ctx context.Context) (*HubCommunityWorker, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HubCommunityWorkerCreate) createSpec() (*HubCommunityWorker, *sqlgraph.CreateSpec) {
	var (
		_node = &HubCommunityWorker{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hubcommunityworker.Table, sqlgraph.NewFieldSpec(hubcommunityworker.FieldID, field.TypeInt64))
	)
	_spec.Schema = _c.schemaConfig.HubCommunityWorker
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hubcommunityworker.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hubcommunityworker.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublisherUserID(); ok {
		_spec.SetField(hubcommunityworker.FieldPublisherUserID, field.TypeInt64, value)
		_node.PublisherUserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(hubcommunityworker.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(hubcommunityworker.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(hubcommunityworker.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(hubcommunityworker.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Handbook(); ok {
		_spec.SetField(hubcommunityworker.FieldHandbook, field.TypeJSON, value)
		_node.Handbook = value
	}
	if value, ok := _c.mutation.Playbooks(); ok {
		_spec.SetField(hubcommunityworker.FieldPlaybooks, field.TypeJSON, value)
		_node.Playbooks = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(hubcommunityworker.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.InstallCount(); ok {
		_spec.SetField(hubcommunityworker.FieldInstallCount, field.TypeInt, value)
		_node.InstallCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(hubcommunityworker.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hubcommunityworker.ReviewsTable,
			Columns: []string{hubcommunityworker.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubcommunityreview.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubCommunityReview
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubCommunityWorker.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubCommunityWorkerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubCommunityWorkerCreate) OnConflict(opts ...sql.ConflictOption) *HubCommunityWorkerUpsertOne {
	_c.conflict = opts
	return &HubCommunityWorkerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubCommunityWorkerCreate) OnConflictColumns(columns ...string) *HubCommunityWorkerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubCommunityWorkerUpsertOne{
		create: _c,
	}
}

type (
	// HubCommunityWorkerUpsertOne is the builder for "upsert"-ing
	//  one HubCommunityWorker node.
	HubCommunityWorkerUpsertOne struct {
		create *HubCommunityWorkerCreate
	}

	// HubCommunityWorkerUpsert is the "OnConflict" setter.
	HubCommunityWorkerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityWorkerUpsert) SetUpdatedAt(v time.Time) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateUpdatedAt() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldUpdatedAt)
	return u
}

// SetPublisherUserID sets the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsert) SetPublisherUserID(v int64) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldPublisherUserID, v)
	return u
}

// UpdatePublisherUserID sets the "publisher_user_id" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdatePublisherUserID() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldPublisherUserID)
	return u
}

// AddPublisherUserID adds v to the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsert) AddPublisherUserID(v int64) *HubCommunityWorkerUpsert {
	u.Add(hubcommunityworker.FieldPublisherUserID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *HubCommunityWorkerUpsert) SetTitle(v string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateTitle() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *HubCommunityWorkerUpsert) SetDescription(v string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateDescription() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *HubCommunityWorkerUpsert) ClearDescription() *HubCommunityWorkerUpsert {
	u.SetNull(hubcommunityworker.FieldDescription)
	return u
}

// SetDomain sets the "domain" field.
func (u *HubCommunityWorkerUpsert) SetDomain(v string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateDomain() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldDomain)
	return u
}

// SetScope sets the "scope" field.
func (u *HubCommunityWorkerUpsert) SetScope(v string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateScope() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldScope)
	return u
}

// ClearScope clears the value of the "scope" field.
func (u *HubCommunityWorkerUpsert) ClearScope() *HubCommunityWorkerUpsert {
	u.SetNull(hubcommunityworker.FieldScope)
	return u
}

// SetHandbook sets the "handbook" field.
func (u *HubCommunityWorkerUpsert) SetHandbook(v map[string]interface{}) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldHandbook, v)
	return u
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateHandbook() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldHandbook)
	return u
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubCommunityWorkerUpsert) ClearHandbook() *HubCommunityWorkerUpsert {
	u.SetNull(hubcommunityworker.FieldHandbook)
	return u
}

// SetPlaybooks sets the "playbooks" field.
func (u *HubCommunityWorkerUpsert) SetPlaybooks(v map[string]interface{}) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldPlaybooks, v)
	return u
}

// UpdatePlaybooks sets the "playbooks" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdatePlaybooks() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldPlaybooks)
	return u
}

// ClearPlaybooks clears the value of the "playbooks" field.
func (u *HubCommunityWorkerUpsert) ClearPlaybooks() *HubCommunityWorkerUpsert {
	u.SetNull(hubcommunityworker.FieldPlaybooks)
	return u
}

// SetTags sets the "tags" field.
func (u *HubCommunityWorkerUpsert) SetTags(v []string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateTags() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *HubCommunityWorkerUpsert) ClearTags() *HubCommunityWorkerUpsert {
	u.SetNull(hubcommunityworker.FieldTags)
	return u
}

// SetInstallCount sets the "install_count" field.
func (u *HubCommunityWorkerUpsert) SetInstallCount(v int) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldInstallCount, v)
	return u
}

// UpdateInstallCount sets the "install_count" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateInstallCount() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldInstallCount)
	return u
}

// AddInstallCount adds v to the "install_count" field.
func (u *HubCommunityWorkerUpsert) AddInstallCount(v int) *HubCommunityWorkerUpsert {
	u.Add(hubcommunityworker.FieldInstallCount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *HubCommunityWorkerUpsert) SetStatus(v string) *HubCommunityWorkerUpsert {
	u.Set(hubcommunityworker.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsert) UpdateStatus() *HubCommunityWorkerUpsert {
	u.SetExcluded(hubcommunityworker.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubCommunityWorkerUpsertOne) UpdateNewValues() *HubCommunityWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hubcommunityworker.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HubCommunityWorkerUpsertOne) Ignore() *HubCommunityWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubCommunityWorkerUpsertOne) DoNothing() *HubCommunityWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubCommunityWorkerCreate.OnConflict
// documentation for more info.
func (u *HubCommunityWorkerUpsertOne) Update(set func(*HubCommunityWorkerUpsert)) *HubCommunityWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubCommunityWorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityWorkerUpsertOne) SetUpdatedAt(v time.Time) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateUpdatedAt() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublisherUserID sets the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsertOne) SetPublisherUserID(v int64) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetPublisherUserID(v)
	})
}

// AddPublisherUserID adds v to the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsertOne) AddPublisherUserID(v int64) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.AddPublisherUserID(v)
	})
}

// UpdatePublisherUserID sets the "publisher_user_id" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdatePublisherUserID() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdatePublisherUserID()
	})
}

// SetTitle sets the "title" field.
func (u *HubCommunityWorkerUpsertOne) SetTitle(v string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateTitle() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *HubCommunityWorkerUpsertOne) SetDescription(v string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateDescription() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HubCommunityWorkerUpsertOne) ClearDescription() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearDescription()
	})
}

// SetDomain sets the "domain" field.
func (u *HubCommunityWorkerUpsertOne) SetDomain(v string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateDomain() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateDomain()
	})
}

// SetScope sets the "scope" field.
func (u *HubCommunityWorkerUpsertOne) SetScope(v string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateScope() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *HubCommunityWorkerUpsertOne) ClearScope() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearScope()
	})
}

// SetHandbook sets the "handbook" field.
func (u *HubCommunityWorkerUpsertOne) SetHandbook(v map[string]interface{}) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetHandbook(v)
	})
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateHandbook() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateHandbook()
	})
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubCommunityWorkerUpsertOne) ClearHandbook() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearHandbook()
	})
}

// SetPlaybooks sets the "playbooks" field.
func (u *HubCommunityWorkerUpsertOne) SetPlaybooks(v map[string]interface{}) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetPlaybooks(v)
	})
}

// UpdatePlaybooks sets the "playbooks" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdatePlaybooks() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdatePlaybooks()
	})
}

// ClearPlaybooks clears the value of the "playbooks" field.
func (u *HubCommunityWorkerUpsertOne) ClearPlaybooks() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearPlaybooks()
	})
}

// SetTags sets the "tags" field.
func (u *HubCommunityWorkerUpsertOne) SetTags(v []string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateTags() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *HubCommunityWorkerUpsertOne) ClearTags() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearTags()
	})
}

// SetInstallCount sets the "install_count" field.
func (u *HubCommunityWorkerUpsertOne) SetInstallCount(v int) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetInstallCount(v)
	})
}

// AddInstallCount adds v to the "install_count" field.
func (u *HubCommunityWorkerUpsertOne) AddInstallCount(v int) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.AddInstallCount(v)
	})
}

// UpdateInstallCount sets the "install_count" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateInstallCount() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateInstallCount()
	})
}

// SetStatus sets the "status" field.
func (u *HubCommunityWorkerUpsertOne) SetStatus(v string) *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertOne) UpdateStatus() *HubCommunityWorkerUpsertOne {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *HubCommunityWorkerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubCommunityWorkerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubCommunityWorkerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HubCommunityWorkerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HubCommunityWorkerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HubCommunityWorkerCreateBulk is the builder for creating many HubCommunityWorker entities in bulk.
type HubCommunityWorkerCreateBulk struct {
	config
	err      error
	builders []*HubCommunityWorkerCreate
	conflict []sql.ConflictOption
}

// Save creates the HubCommunityWorker entities in the database.
func (_c *HubCommunityWorkerCreateBulk) Save(ctx context.Context) ([]*HubCommunityWorker, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HubCommunityWorker, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HubCommunityWorkerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HubCommunityWorkerCreateBulk) SaveX(ctx context.Context) []*HubCommunityWorker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubCommunityWorkerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubCommunityWorkerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubCommunityWorker.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubCommunityWorkerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubCommunityWorkerCreateBulk) OnConflict(opts ...sql.ConflictOption) *HubCommunityWorkerUpsertBulk {
	_c.conflict = opts
	return &HubCommunityWorkerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubCommunityWorkerCreateBulk) OnConflictColumns(columns ...string) *HubCommunityWorkerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubCommunityWorkerUpsertBulk{
		create: _c,
	}
}

// HubCommunityWorkerUpsertBulk is the builder for "upsert"-ing
// a bulk of HubCommunityWorker nodes.
type HubCommunityWorkerUpsertBulk struct {
	create *HubCommunityWorkerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubCommunityWorkerUpsertBulk) UpdateNewValues() *HubCommunityWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hubcommunityworker.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubCommunityWorker.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HubCommunityWorkerUpsertBulk) Ignore() *HubCommunityWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubCommunityWorkerUpsertBulk) DoNothing() *HubCommunityWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubCommunityWorkerCreateBulk.OnConflict
// documentation for more info.
func (u *HubCommunityWorkerUpsertBulk) Update(set func(*HubCommunityWorkerUpsert)) *HubCommunityWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubCommunityWorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityWorkerUpsertBulk) SetUpdatedAt(v time.Time) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateUpdatedAt() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublisherUserID sets the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsertBulk) SetPublisherUserID(v int64) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetPublisherUserID(v)
	})
}

// AddPublisherUserID adds v to the "publisher_user_id" field.
func (u *HubCommunityWorkerUpsertBulk) AddPublisherUserID(v int64) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.AddPublisherUserID(v)
	})
}

// UpdatePublisherUserID sets the "publisher_user_id" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdatePublisherUserID() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdatePublisherUserID()
	})
}

// SetTitle sets the "title" field.
func (u *HubCommunityWorkerUpsertBulk) SetTitle(v string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateTitle() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *HubCommunityWorkerUpsertBulk) SetDescription(v string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateDescription() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HubCommunityWorkerUpsertBulk) ClearDescription() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearDescription()
	})
}

// SetDomain sets the "domain" field.
func (u *HubCommunityWorkerUpsertBulk) SetDomain(v string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateDomain() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateDomain()
	})
}

// SetScope sets the "scope" field.
func (u *HubCommunityWorkerUpsertBulk) SetScope(v string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateScope() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *HubCommunityWorkerUpsertBulk) ClearScope() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearScope()
	})
}

// SetHandbook sets the "handbook" field.
func (u *HubCommunityWorkerUpsertBulk) SetHandbook(v map[string]interface{}) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetHandbook(v)
	})
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateHandbook() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateHandbook()
	})
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubCommunityWorkerUpsertBulk) ClearHandbook() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearHandbook()
	})
}

// SetPlaybooks sets the "playbooks" field.
func (u *HubCommunityWorkerUpsertBulk) SetPlaybooks(v map[string]interface{}) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetPlaybooks(v)
	})
}

// UpdatePlaybooks sets the "playbooks" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdatePlaybooks() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdatePlaybooks()
	})
}

// ClearPlaybooks clears the value of the "playbooks" field.
func (u *HubCommunityWorkerUpsertBulk) ClearPlaybooks() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearPlaybooks()
	})
}

// SetTags sets the "tags" field.
func (u *HubCommunityWorkerUpsertBulk) SetTags(v []string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateTags() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *HubCommunityWorkerUpsertBulk) ClearTags() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.ClearTags()
	})
}

// SetInstallCount sets the "install_count" field.
func (u *HubCommunityWorkerUpsertBulk) SetInstallCount(v int) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetInstallCount(v)
	})
}

// AddInstallCount adds v to the "install_count" field.
func (u *HubCommunityWorkerUpsertBulk) AddInstallCount(v int) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.AddInstallCount(v)
	})
}

// UpdateInstallCount sets the "install_count" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateInstallCount() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateInstallCount()
	})
}

// SetStatus sets the "status" field.
func (u *HubCommunityWorkerUpsertBulk) SetStatus(v string) *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubCommunityWorkerUpsertBulk) UpdateStatus() *HubCommunityWorkerUpsertBulk {
	return u.Update(func(s *HubCommunityWorkerUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *HubCommunityWorkerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HubCommunityWorkerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubCommunityWorkerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubCommunityWorkerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
