// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
)

// HubCommunityReviewCreate is the builder for creating a HubCommunityReview entity.
type HubCommunityReviewCreate struct {
	config
	mutation *HubCommunityReviewMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HubCommunityReviewCreate) SetCreatedAt(v time.Time) *HubCommunityReviewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HubCommunityReviewCreate) SetNillableCreatedAt(v *time.Time) *HubCommunityReviewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HubCommunityReviewCreate) SetUpdatedAt(v time.Time) *HubCommunityReviewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HubCommunityReviewCreate) SetNillableUpdatedAt(v *time.Time) *HubCommunityReviewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkerID sets the "worker_id" field.
func (_c *HubCommunityReviewCreate) SetWorkerID(v int64) *HubCommunityReviewCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *HubCommunityReviewCreate) SetUserID(v int64) *HubCommunityReviewCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *HubCommunityReviewCreate) SetRating(v int) *HubCommunityReviewCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *HubCommunityReviewCreate) SetComment(v string) *HubCommunityReviewCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *HubCommunityReviewCreate) SetNillableComment(v *string) *HubCommunityReviewCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetCommunityWorkerID sets the "community_worker" edge to the HubCommunityWorker entity by ID.
func (_c *HubCommunityReviewCreate) SetCommunityWorkerID(id int64) *HubCommunityReviewCreate {
	_c.mutation.SetCommunityWorkerID(id)
	return _c
}

// SetCommunityWorker sets the "community_worker" edge to the HubCommunityWorker entity.
func (_c *HubCommunityReviewCreate) SetCommunityWorker(v *HubCommunityWorker) *HubCommunityReviewCreate {
	return _c.SetCommunityWorkerID(v.ID)
}

// Mutation returns the HubCommunityReviewMutation object of the builder.
func (_c *HubCommunityReviewCreate) Mutation() *HubCommunityReviewMutation {
	return _c.mutation
}

// Save creates the HubCommunityReview in the database.
func (_c *HubCommunityReviewCreate) Save(ctx context.Context) (*HubCommunityReview, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HubCommunityReviewCreate) SaveX(ctx context.Context) *HubCommunityReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubCommunityReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubCommunityReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HubCommunityReviewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hubcommunityreview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := hubcommunityreview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HubCommunityReviewCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HubCommunityReview.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HubCommunityReview.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkerID(); !ok {
		return &ValidationError{Name: "worker_id", err: errors.New(`ent: missing required field "HubCommunityReview.worker_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "HubCommunityReview.user_id"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "HubCommunityReview.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := hubcommunityreview.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "HubCommunityReview.rating": %w`, err)}
		}
	}
	if len(_c.mutation.CommunityWorkerIDs()) == 0 {
		return &ValidationError{Name: "community_worker", err: errors.New(`ent: missing required edge "HubCommunityReview.community_worker"`)}
	}
	return nil
}

func (_c *HubCommunityReviewCreate) sqlSave(ctx context.Context) (*HubCommunityReview, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HubCommunityReviewCreate) createSpec() (*HubCommunityReview, *sqlgraph.CreateSpec) {
	var (
		_node = &HubCommunityReview{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hubcommunityreview.Table, sqlgraph.NewFieldSpec(hubcommunityreview.FieldID, field.TypeInt64))
	)
	_spec.Schema = _c.schemaConfig.HubCommunityReview
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hubcommunityreview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hubcommunityreview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(hubcommunityreview.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(hubcommunityreview.FieldRating, field.TypeInt, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(hubcommunityreview.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if nodes := _c.mutation.CommunityWorkerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubcommunityreview.CommunityWorkerTable,
			Columns: []string{hubcommunityreview.CommunityWorkerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubcommunityworker.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubCommunityReview
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubCommunityReview.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubCommunityReviewUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubCommunityReviewCreate) OnConflict(opts ...sql.ConflictOption) *HubCommunityReviewUpsertOne {
	_c.conflict = opts
	return &HubCommunityReviewUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubCommunityReviewCreate) OnConflictColumns(columns ...string) *HubCommunityReviewUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubCommunityReviewUpsertOne{
		create: _c,
	}
}

type (
	// HubCommunityReviewUpsertOne is the builder for "upsert"-ing
	//  one HubCommunityReview node.
	HubCommunityReviewUpsertOne struct {
		create *HubCommunityReviewCreate
	}

	// HubCommunityReviewUpsert is the "OnConflict" setter.
	HubCommunityReviewUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityReviewUpsert) SetUpdatedAt(v time.Time) *HubCommunityReviewUpsert {
	u.Set(hubcommunityreview.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityReviewUpsert) UpdateUpdatedAt() *HubCommunityReviewUpsert {
	u.SetExcluded(hubcommunityreview.FieldUpdatedAt)
	return u
}

// SetWorkerID sets the "worker_id" field.
func (u *HubCommunityReviewUpsert) SetWorkerID(v int64) *HubCommunityReviewUpsert {
	u.Set(hubcommunityreview.FieldWorkerID, v)
	return u
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsert) UpdateWorkerID() *HubCommunityReviewUpsert {
	u.SetExcluded(hubcommunityreview.FieldWorkerID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *HubCommunityReviewUpsert) SetUserID(v int64) *HubCommunityReviewUpsert {
	u.Set(hubcommunityreview.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsert) UpdateUserID() *HubCommunityReviewUpsert {
	u.SetExcluded(hubcommunityreview.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *HubCommunityReviewUpsert) AddUserID(v int64) *HubCommunityReviewUpsert {
	u.Add(hubcommunityreview.FieldUserID, v)
	return u
}

// SetRating sets the "rating" field.
func (u *HubCommunityReviewUpsert) SetRating(v int) *HubCommunityReviewUpsert {
	u.Set(hubcommunityreview.FieldRating, v)
	return u
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *HubCommunityReviewUpsert) UpdateRating() *HubCommunityReviewUpsert {
	u.SetExcluded(hubcommunityreview.FieldRating)
	return u
}

// AddRating adds v to the "rating" field.
func (u *HubCommunityReviewUpsert) AddRating(v int) *HubCommunityReviewUpsert {
	u.Add(hubcommunityreview.FieldRating, v)
	return u
}

// SetComment sets the "comment" field.
func (u *HubCommunityReviewUpsert) SetComment(v string) *HubCommunityReviewUpsert {
	u.Set(hubcommunityreview.FieldComment, v)
	return u
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *HubCommunityReviewUpsert) UpdateComment() *HubCommunityReviewUpsert {
	u.SetExcluded(hubcommunityreview.FieldComment)
	return u
}

// ClearComment clears the value of the "comment" field.
func (u *HubCommunityReviewUpsert) ClearComment() *HubCommunityReviewUpsert {
	u.SetNull(hubcommunityreview.FieldComment)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubCommunityReviewUpsertOne) UpdateNewValues() *HubCommunityReviewUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hubcommunityreview.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HubCommunityReviewUpsertOne) Ignore() *HubCommunityReviewUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubCommunityReviewUpsertOne) DoNothing() *HubCommunityReviewUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubCommunityReviewCreate.OnConflict
// documentation for more info.
func (u *HubCommunityReviewUpsertOne) Update(set func(*HubCommunityReviewUpsert)) *HubCommunityReviewUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubCommunityReviewUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityReviewUpsertOne) SetUpdatedAt(v time.Time) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertOne) UpdateUpdatedAt() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *HubCommunityReviewUpsertOne) SetWorkerID(v int64) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertOne) UpdateWorkerID() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateWorkerID()
	})
}

// SetUserID sets the "user_id" field.
func (u *HubCommunityReviewUpsertOne) SetUserID(v int64) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *HubCommunityReviewUpsertOne) AddUserID(v int64) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertOne) UpdateUserID() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateUserID()
	})
}

// SetRating sets the "rating" field.
func (u *HubCommunityReviewUpsertOne) SetRating(v int) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *HubCommunityReviewUpsertOne) AddRating(v int) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertOne) UpdateRating() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateRating()
	})
}

// SetComment sets the "comment" field.
func (u *HubCommunityReviewUpsertOne) SetComment(v string) *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertOne) UpdateComment() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateComment()
	})
}

// ClearComment clears the value of the "comment" field.
func (u *HubCommunityReviewUpsertOne) ClearComment() *HubCommunityReviewUpsertOne {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.ClearComment()
	})
}

// Exec executes the query.
func (u *HubCommunityReviewUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubCommunityReviewCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubCommunityReviewUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HubCommunityReviewUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HubCommunityReviewUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HubCommunityReviewCreateBulk is the builder for creating many HubCommunityReview entities in bulk.
type HubCommunityReviewCreateBulk struct {
	config
	err      error
	builders []*HubCommunityReviewCreate
	conflict []sql.ConflictOption
}

// Save creates the HubCommunityReview entities in the database.
func (_c *HubCommunityReviewCreateBulk) Save(ctx context.Context) ([]*HubCommunityReview, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HubCommunityReview, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HubCommunityReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HubCommunityReviewCreateBulk) SaveX(ctx context.Context) []*HubCommunityReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubCommunityReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubCommunityReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubCommunityReview.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubCommunityReviewUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubCommunityReviewCreateBulk) OnConflict(opts ...sql.ConflictOption) *HubCommunityReviewUpsertBulk {
	_c.conflict = opts
	return &HubCommunityReviewUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubCommunityReviewCreateBulk) OnConflictColumns(columns ...string) *HubCommunityReviewUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubCommunityReviewUpsertBulk{
		create: _c,
	}
}

// HubCommunityReviewUpsertBulk is the builder for "upsert"-ing
// a bulk of HubCommunityReview nodes.
type HubCommunityReviewUpsertBulk struct {
	create *HubCommunityReviewCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubCommunityReviewUpsertBulk) UpdateNewValues() *HubCommunityReviewUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hubcommunityreview.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubCommunityReview.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HubCommunityReviewUpsertBulk) Ignore() *HubCommunityReviewUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubCommunityReviewUpsertBulk) DoNothing() *HubCommunityReviewUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubCommunityReviewCreateBulk.OnConflict
// documentation for more info.
func (u *HubCommunityReviewUpsertBulk) Update(set func(*HubCommunityReviewUpsert)) *HubCommunityReviewUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubCommunityReviewUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubCommunityReviewUpsertBulk) SetUpdatedAt(v time.Time) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertBulk) UpdateUpdatedAt() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *HubCommunityReviewUpsertBulk) SetWorkerID(v int64) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertBulk) UpdateWorkerID() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateWorkerID()
	})
}

// SetUserID sets the "user_id" field.
func (u *HubCommunityReviewUpsertBulk) SetUserID(v int64) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *HubCommunityReviewUpsertBulk) AddUserID(v int64) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertBulk) UpdateUserID() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateUserID()
	})
}

// SetRating sets the "rating" field.
func (u *HubCommunityReviewUpsertBulk) SetRating(v int) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *HubCommunityReviewUpsertBulk) AddRating(v int) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertBulk) UpdateRating() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateRating()
	})
}

// SetComment sets the "comment" field.
func (u *HubCommunityReviewUpsertBulk) SetComment(v string) *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *HubCommunityReviewUpsertBulk) UpdateComment() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.UpdateComment()
	})
}

// ClearComment clears the value of the "comment" field.
func (u *HubCommunityReviewUpsertBulk) ClearComment() *HubCommunityReviewUpsertBulk {
	return u.Update(func(s *HubCommunityReviewUpsert) {
		s.ClearComment()
	})
}

// Exec executes the query.
func (u *HubCommunityReviewUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HubCommunityReviewCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubCommunityReviewCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubCommunityReviewUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
