// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubLockQuery is the builder for querying HubLock entities.
type HubLockQuery struct {
	config
	ctx          *QueryContext
	order        []hublock.OrderOption
	inters       []Interceptor
	predicates   []predicate.HubLock
	withBusiness *HubBusinessQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HubLockQuery builder.
func (_q *HubLockQuery) Where(ps ...predicate.HubLock) *HubLockQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HubLockQuery) Limit(limit int) *HubLockQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HubLockQuery) Offset(offset int) *HubLockQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HubLockQuery) Unique(unique bool) *HubLockQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HubLockQuery) Order(o ...hublock.OrderOption) *HubLockQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBusiness chains the current query on the "business" edge.
func (_q *HubLockQuery) QueryBusiness() *HubBusinessQuery {
	query := (&HubBusinessClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hublock.Table, hublock.FieldID, selector),
			sqlgraph.To(hubbusiness.Table, hubbusiness.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hublock.BusinessTable, hublock.BusinessColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.HubBusiness
		step.Edge.Schema = schemaConfig.HubLock
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HubLock entity from the query.
// Returns a *NotFoundError when no HubLock was found.
func (_q *HubLockQuery) First(ctx context.Context) (*HubLock, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hublock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HubLockQuery) FirstX(ctx context.Context) *HubLock {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HubLock ID from the query.
// Returns a *NotFoundError when no HubLock ID was found.
func (_q *HubLockQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hublock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HubLockQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HubLock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HubLock entity is found.
// Returns a *NotFoundError when no HubLock entities are found.
func (_q *HubLockQuery) Only(ctx context.Context) (*HubLock, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hublock.Label}
	default:
		return nil, &NotSingularError{hublock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HubLockQuery) OnlyX(ctx context.Context) *HubLock {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HubLock ID in the query.
// Returns a *NotSingularError when more than one HubLock ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HubLockQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hublock.Label}
	default:
		err = &NotSingularError{hublock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HubLockQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HubLocks.
func (_q *HubLockQuery) All(ctx context.Context) ([]*HubLock, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HubLock, *HubLockQuery]()
	return withInterceptors[[]*HubLock](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HubLockQuery) AllX(ctx context.Context) []*HubLock {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HubLock IDs.
func (_q *HubLockQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(hublock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HubLockQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HubLockQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HubLockQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HubLockQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HubLockQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HubLockQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HubLockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HubLockQuery) Clone() *HubLockQuery {
	if _q == nil {
		return nil
	}
	return &HubLockQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]hublock.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.HubLock{}, _q.predicates...),
		withBusiness: _q.withBusiness.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBusiness tells the query-builder to eager-load the nodes that are connected to
// the "business" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HubLockQuery) WithBusiness(opts ...func(*HubBusinessQuery)) *HubLockQuery {
	query := (&HubBusinessClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBusiness = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HubLock.Query().
//		GroupBy(hublock.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HubLockQuery) GroupBy(field string, fields ...string) *HubLockGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HubLockGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = hublock.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.HubLock.Query().
//		Select(hublock.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *HubLockQuery) Select(fields ...string) *HubLockSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HubLockSelect{HubLockQuery: _q}
	sbuild.label = hublock.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HubLockSelect configured with the given aggregations.
func (_q *HubLockQuery) Aggregate(fns ...AggregateFunc) *HubLockSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HubLockQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !hublock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *HubLockQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HubLock, error) {
	var (
		nodes       = []*HubLock{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withBusiness != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HubLock).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HubLock{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.HubLock
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBusiness; query != nil {
		if err := _q.loadBusiness(ctx, query, nodes, nil,
			func(n *HubLock, e *HubBusiness) { n.Edges.Business = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HubLockQuery) loadBusiness(ctx context.Context, query *HubBusinessQuery, nodes []*HubLock, init func(*HubLock), assign func(*HubLock, *HubBusiness)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*HubLock)
	for i := range nodes {
		fk := nodes[i].BusinessID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hubbusiness.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "business_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *HubLockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.HubLock
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HubLockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hublock.Table, hublock.Columns, sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hublock.FieldID)
		for i := range fields {
			if fields[i] != hublock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBusiness != nil {
			_spec.Node.AddColumnOnce(hublock.FieldBusinessID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HubLockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(hublock.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = hublock.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.HubLock)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HubLockGroupBy is the group-by builder for HubLock entities.
type HubLockGroupBy struct {
	selector
	build *HubLockQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HubLockGroupBy) Aggregate(fns ...AggregateFunc) *HubLockGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HubLockGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HubLockQuery, *HubLockGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HubLockGroupBy) sqlScan(ctx context.Context, root *HubLockQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HubLockSelect is the builder for selecting fields of HubLock entities.
type HubLockSelect struct {
	*HubLockQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HubLockSelect) Aggregate(fns ...AggregateFunc) *HubLockSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HubLockSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HubLockQuery, *HubLockSelect](ctx, _s.HubLockQuery, _s, _s.inters, v)
}

func (_s *HubLockSelect) sqlScan(ctx context.Context, root *HubLockQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
