// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubLockDelete is the builder for deleting a HubLock entity.
type HubLockDelete struct {
	config
	hooks    []Hook
	mutation *HubLockMutation
}

// Where appends a list predicates to the HubLockDelete builder.
func (_d *HubLockDelete) Where(ps ...predicate.HubLock) *HubLockDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HubLockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubLockDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HubLockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hublock.Table, sqlgraph.NewFieldSpec(hublock.FieldID, field.TypeInt64))
	_spec.Node.Schema = _d.schemaConfig.HubLock
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HubLockDeleteOne is the builder for deleting a single HubLock entity.
type HubLockDeleteOne struct {
	_d *HubLockDelete
}

// Where appends a list predicates to the HubLockDelete builder.
func (_d *HubLockDeleteOne) Where(ps ...predicate.HubLock) *HubLockDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HubLockDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hublock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HubLockDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
