// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubworker"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// HubWorkerUpdate is the builder for updating HubWorker entities.
type HubWorkerUpdate struct {
	config
	hooks    []Hook
	mutation *HubWorkerMutation
}

// Where appends a list predicates to the HubWorkerUpdate builder.
func (_u *HubWorkerUpdate) Where(ps ...predicate.HubWorker) *HubWorkerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HubWorkerUpdate) SetUpdatedAt(v time.Time) *HubWorkerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBusinessID sets the "business_id" field.
func (_u *HubWorkerUpdate) SetBusinessID(v int64) *HubWorkerUpdate {
	_u.mutation.SetBusinessID(v)
	return _u
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableBusinessID(v *int64) *HubWorkerUpdate {
	if v != nil {
		_u.SetBusinessID(*v)
	}
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *HubWorkerUpdate) SetWorkerID(v string) *HubWorkerUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableWorkerID(v *string) *HubWorkerUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *HubWorkerUpdate) SetVersion(v string) *HubWorkerUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableVersion(v *string) *HubWorkerUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *HubWorkerUpdate) ClearVersion() *HubWorkerUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *HubWorkerUpdate) SetLastHeartbeatAt(v time.Time) *HubWorkerUpdate {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableLastHeartbeatAt(v *time.Time) *HubWorkerUpdate {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *HubWorkerUpdate) ClearLastHeartbeatAt() *HubWorkerUpdate {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HubWorkerUpdate) SetStatus(v string) *HubWorkerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableStatus(v *string) *HubWorkerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *HubWorkerUpdate) SetHost(v string) *HubWorkerUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableHost(v *string) *HubWorkerUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *HubWorkerUpdate) ClearHost() *HubWorkerUpdate {
	_u.mutation.ClearHost()
	return _u
}

// SetPid sets the "pid" field.
func (_u *HubWorkerUpdate) SetPid(v int) *HubWorkerUpdate {
	_u.mutation.ResetPid()
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillablePid(v *int) *HubWorkerUpdate {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// AddPid adds value to the "pid" field.
func (_u *HubWorkerUpdate) AddPid(v int) *HubWorkerUpdate {
	_u.mutation.AddPid(v)
	return _u
}

// ClearPid clears the value of the "pid" field.
func (_u *HubWorkerUpdate) ClearPid() *HubWorkerUpdate {
	_u.mutation.ClearPid()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *HubWorkerUpdate) SetOwner(v string) *HubWorkerUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *HubWorkerUpdate) SetNillableOwner(v *string) *HubWorkerUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *HubWorkerUpdate) ClearOwner() *HubWorkerUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// SetHandbook sets the "handbook" field.
func (_u *HubWorkerUpdate) SetHandbook(v map[string]interface{}) *HubWorkerUpdate {
	_u.mutation.SetHandbook(v)
	return _u
}

// ClearHandbook clears the value of the "handbook" field.
func (_u *HubWorkerUpdate) ClearHandbook() *HubWorkerUpdate {
	_u.mutation.ClearHandbook()
	return _u
}

// SetBusiness sets the "business" edge to the HubBusiness entity.
func (_u *HubWorkerUpdate) SetBusiness(v *HubBusiness) *HubWorkerUpdate {
	return _u.SetBusinessID(v.ID)
}

// Mutation returns the HubWorkerMutation object of the builder.
func (_u *HubWorkerUpdate) Mutation() *HubWorkerMutation {
	return _u.mutation
}

// ClearBusiness clears the "business" edge to the HubBusiness entity.
func (_u *HubWorkerUpdate) ClearBusiness() *HubWorkerUpdate {
	_u.mutation.ClearBusiness()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HubWorkerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubWorkerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HubWorkerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubWorkerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubWorkerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hubworker.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubWorkerUpdate) check() error {
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := hubworker.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "HubWorker.worker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := hubworker.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "HubWorker.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := hubworker.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubWorker.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := hubworker.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "HubWorker.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := hubworker.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "HubWorker.owner": %w`, err)}
		}
	}
	if _u.mutation.BusinessCleared() && len(_u.mutation.BusinessIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HubWorker.business"`)
	}
	return nil
}

func (_u *HubWorkerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubworker.Table, hubworker.Columns, sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hubworker.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(hubworker.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(hubworker.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(hubworker.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(hubworker.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(hubworker.FieldLastHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hubworker.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(hubworker.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(hubworker.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(hubworker.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPid(); ok {
		_spec.AddField(hubworker.FieldPid, field.TypeInt, value)
	}
	if _u.mutation.PidCleared() {
		_spec.ClearField(hubworker.FieldPid, field.TypeInt)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(hubworker.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(hubworker.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Handbook(); ok {
		_spec.SetField(hubworker.FieldHandbook, field.TypeJSON, value)
	}
	if _u.mutation.HandbookCleared() {
		_spec.ClearField(hubworker.FieldHandbook, field.TypeJSON)
	}
	if _u.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubworker.BusinessTable,
			Columns: []string{hubworker.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubworker.BusinessTable,
			Columns: []string{hubworker.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.HubWorker
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubworker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HubWorkerUpdateOne is the builder for updating a single HubWorker entity.
type HubWorkerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HubWorkerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HubWorkerUpdateOne) SetUpdatedAt(v time.Time) *HubWorkerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBusinessID sets the "business_id" field.
func (_u *HubWorkerUpdateOne) SetBusinessID(v int64) *HubWorkerUpdateOne {
	_u.mutation.SetBusinessID(v)
	return _u
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableBusinessID(v *int64) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetBusinessID(*v)
	}
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *HubWorkerUpdateOne) SetWorkerID(v string) *HubWorkerUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableWorkerID(v *string) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *HubWorkerUpdateOne) SetVersion(v string) *HubWorkerUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableVersion(v *string) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *HubWorkerUpdateOne) ClearVersion() *HubWorkerUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *HubWorkerUpdateOne) SetLastHeartbeatAt(v time.Time) *HubWorkerUpdateOne {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableLastHeartbeatAt(v *time.Time) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *HubWorkerUpdateOne) ClearLastHeartbeatAt() *HubWorkerUpdateOne {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HubWorkerUpdateOne) SetStatus(v string) *HubWorkerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableStatus(v *string) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *HubWorkerUpdateOne) SetHost(v string) *HubWorkerUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableHost(v *string) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *HubWorkerUpdateOne) ClearHost() *HubWorkerUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// SetPid sets the "pid" field.
func (_u *HubWorkerUpdateOne) SetPid(v int) *HubWorkerUpdateOne {
	_u.mutation.ResetPid()
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillablePid(v *int) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// AddPid adds value to the "pid" field.
func (_u *HubWorkerUpdateOne) AddPid(v int) *HubWorkerUpdateOne {
	_u.mutation.AddPid(v)
	return _u
}

// ClearPid clears the value of the "pid" field.
func (_u *HubWorkerUpdateOne) ClearPid() *HubWorkerUpdateOne {
	_u.mutation.ClearPid()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *HubWorkerUpdateOne) SetOwner(v string) *HubWorkerUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *HubWorkerUpdateOne) SetNillableOwner(v *string) *HubWorkerUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *HubWorkerUpdateOne) ClearOwner() *HubWorkerUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// SetHandbook sets the "handbook" field.
func (_u *HubWorkerUpdateOne) SetHandbook(v map[string]interface{}) *HubWorkerUpdateOne {
	_u.mutation.SetHandbook(v)
	return _u
}

// ClearHandbook clears the value of the "handbook" field.
func (_u *HubWorkerUpdateOne) ClearHandbook() *HubWorkerUpdateOne {
	_u.mutation.ClearHandbook()
	return _u
}

// SetBusiness sets the "business" edge to the HubBusiness entity.
func (_u *HubWorkerUpdateOne) SetBusiness(v *HubBusiness) *HubWorkerUpdateOne {
	return _u.SetBusinessID(v.ID)
}

// Mutation returns the HubWorkerMutation object of the builder.
func (_u *HubWorkerUpdateOne) Mutation() *HubWorkerMutation {
	return _u.mutation
}

// ClearBusiness clears the "business" edge to the HubBusiness entity.
func (_u *HubWorkerUpdateOne) ClearBusiness() *HubWorkerUpdateOne {
	_u.mutation.ClearBusiness()
	return _u
}

// Where appends a list predicates to the HubWorkerUpdate builder.
func (_u *HubWorkerUpdateOne) Where(ps ...predicate.HubWorker) *HubWorkerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HubWorkerUpdateOne) Select(field string, fields ...string) *HubWorkerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HubWorker entity.
func (_u *HubWorkerUpdateOne) Save(ctx context.Context) (*HubWorker, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubWorkerUpdateOne) SaveX(ctx context.Context) *HubWorker {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HubWorkerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubWorkerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubWorkerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hubworker.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HubWorkerUpdateOne) check() error {
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := hubworker.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "HubWorker.worker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := hubworker.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "HubWorker.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := hubworker.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubWorker.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := hubworker.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "HubWorker.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := hubworker.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "HubWorker.owner": %w`, err)}
		}
	}
	if _u.mutation.BusinessCleared() && len(_u.mutation.BusinessIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HubWorker.business"`)
	}
	return nil
}

func (_u *HubWorkerUpdateOne) sqlSave(ctx context.Context) (_node *HubWorker, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hubworker.Table, hubworker.Columns, sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HubWorker.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hubworker.FieldID)
		for _, f := range fields {
			if !hubworker.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hubworker.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hubworker.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(hubworker.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(hubworker.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(hubworker.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(hubworker.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(hubworker.FieldLastHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hubworker.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(hubworker.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(hubworker.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(hubworker.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPid(); ok {
		_spec.AddField(hubworker.FieldPid, field.TypeInt, value)
	}
	if _u.mutation.PidCleared() {
		_spec.ClearField(hubworker.FieldPid, field.TypeInt)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(hubworker.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(hubworker.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Handbook(); ok {
		_spec.SetField(hubworker.FieldHandbook, field.TypeJSON, value)
	}
	if _u.mutation.HandbookCleared() {
		_spec.ClearField(hubworker.FieldHandbook, field.TypeJSON)
	}
	if _u.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubworker.BusinessTable,
			Columns: []string{hubworker.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubworker.BusinessTable,
			Columns: []string{hubworker.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _u.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.HubWorker
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &HubWorker{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubworker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
