// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubworker"
)

// HubWorkerCreate is the builder for creating a HubWorker entity.
type HubWorkerCreate struct {
	config
	mutation *HubWorkerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HubWorkerCreate) SetCreatedAt(v time.Time) *HubWorkerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableCreatedAt(v *time.Time) *HubWorkerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HubWorkerCreate) SetUpdatedAt(v time.Time) *HubWorkerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableUpdatedAt(v *time.Time) *HubWorkerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBusinessID sets the "business_id" field.
func (_c *HubWorkerCreate) SetBusinessID(v int64) *HubWorkerCreate {
	_c.mutation.SetBusinessID(v)
	return _c
}

// SetWorkerID sets the "worker_id" field.
func (_c *HubWorkerCreate) SetWorkerID(v string) *HubWorkerCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *HubWorkerCreate) SetVersion(v string) *HubWorkerCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableVersion(v *string) *HubWorkerCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_c *HubWorkerCreate) SetLastHeartbeatAt(v time.Time) *HubWorkerCreate {
	_c.mutation.SetLastHeartbeatAt(v)
	return _c
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableLastHeartbeatAt(v *time.Time) *HubWorkerCreate {
	if v != nil {
		_c.SetLastHeartbeatAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *HubWorkerCreate) SetStatus(v string) *HubWorkerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableStatus(v *string) *HubWorkerCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *HubWorkerCreate) SetHost(v string) *HubWorkerCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableHost(v *string) *HubWorkerCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetPid sets the "pid" field.
func (_c *HubWorkerCreate) SetPid(v int) *HubWorkerCreate {
	_c.mutation.SetPid(v)
	return _c
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillablePid(v *int) *HubWorkerCreate {
	if v != nil {
		_c.SetPid(*v)
	}
	return _c
}

// SetOwner sets the "owner" field.
func (_c *HubWorkerCreate) SetOwner(v string) *HubWorkerCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_c *HubWorkerCreate) SetNillableOwner(v *string) *HubWorkerCreate {
	if v != nil {
		_c.SetOwner(*v)
	}
	return _c
}

// SetHandbook sets the "handbook" field.
func (_c *HubWorkerCreate) SetHandbook(v map[string]interface{}) *HubWorkerCreate {
	_c.mutation.SetHandbook(v)
	return _c
}

// SetBusiness sets the "business" edge to the HubBusiness entity.
func (_c *HubWorkerCreate) SetBusiness(v *HubBusiness) *HubWorkerCreate {
	return _c.SetBusinessID(v.ID)
}

// Mutation returns the HubWorkerMutation object of the builder.
func (_c *HubWorkerCreate) Mutation() *HubWorkerMutation {
	return _c.mutation
}

// Save creates the HubWorker in the database.
func (_c *HubWorkerCreate) Save(ctx context.Context) (*HubWorker, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HubWorkerCreate) SaveX(ctx context.Context) *HubWorker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubWorkerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubWorkerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HubWorkerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hubworker.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := hubworker.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := hubworker.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HubWorkerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HubWorker.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HubWorker.updated_at"`)}
	}
	if _, ok := _c.mutation.BusinessID(); !ok {
		return &ValidationError{Name: "business_id", err: errors.New(`ent: missing required field "HubWorker.business_id"`)}
	}
	if _, ok := _c.mutation.WorkerID(); !ok {
		return &ValidationError{Name: "worker_id", err: errors.New(`ent: missing required field "HubWorker.worker_id"`)}
	}
	if v, ok := _c.mutation.WorkerID(); ok {
		if err := hubworker.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "HubWorker.worker_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := hubworker.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "HubWorker.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HubWorker.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := hubworker.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HubWorker.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := hubworker.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "HubWorker.host": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Owner(); ok {
		if err := hubworker.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "HubWorker.owner": %w`, err)}
		}
	}
	if len(_c.mutation.BusinessIDs()) == 0 {
		return &ValidationError{Name: "business", err: errors.New(`ent: missing required edge "HubWorker.business"`)}
	}
	return nil
}

func (_c *HubWorkerCreate) sqlSave(ctx context.Context) (*HubWorker, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HubWorkerCreate) createSpec() (*HubWorker, *sqlgraph.CreateSpec) {
	var (
		_node = &HubWorker{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hubworker.Table, sqlgraph.NewFieldSpec(hubworker.FieldID, field.TypeInt64))
	)
	_spec.Schema = _c.schemaConfig.HubWorker
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hubworker.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(hubworker.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkerID(); ok {
		_spec.SetField(hubworker.FieldWorkerID, field.TypeString, value)
		_node.WorkerID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(hubworker.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(hubworker.FieldLastHeartbeatAt, field.TypeTime, value)
		_node.LastHeartbeatAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(hubworker.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(hubworker.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Pid(); ok {
		_spec.SetField(hubworker.FieldPid, field.TypeInt, value)
		_node.Pid = &value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(hubworker.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Handbook(); ok {
		_spec.SetField(hubworker.FieldHandbook, field.TypeJSON, value)
		_node.Handbook = value
	}
	if nodes := _c.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hubworker.BusinessTable,
			Columns: []string{hubworker.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hubbusiness.FieldID, field.TypeInt64),
			},
		}
		edge.Schema = _c.schemaConfig.HubWorker
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BusinessID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubWorker.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubWorkerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubWorkerCreate) OnConflict(opts ...sql.ConflictOption) *HubWorkerUpsertOne {
	_c.conflict = opts
	return &HubWorkerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubWorkerCreate) OnConflictColumns(columns ...string) *HubWorkerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubWorkerUpsertOne{
		create: _c,
	}
}

type (
	// HubWorkerUpsertOne is the builder for "upsert"-ing
	//  one HubWorker node.
	HubWorkerUpsertOne struct {
		create *HubWorkerCreate
	}

	// HubWorkerUpsert is the "OnConflict" setter.
	HubWorkerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HubWorkerUpsert) SetUpdatedAt(v time.Time) *HubWorkerUpsert {
	u.Set(hubworker.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateUpdatedAt() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldUpdatedAt)
	return u
}

// SetBusinessID sets the "business_id" field.
func (u *HubWorkerUpsert) SetBusinessID(v int64) *HubWorkerUpsert {
	u.Set(hubworker.FieldBusinessID, v)
	return u
}

// UpdateBusinessID sets the "business_id" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateBusinessID() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldBusinessID)
	return u
}

// SetWorkerID sets the "worker_id" field.
func (u *HubWorkerUpsert) SetWorkerID(v string) *HubWorkerUpsert {
	u.Set(hubworker.FieldWorkerID, v)
	return u
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateWorkerID() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldWorkerID)
	return u
}

// SetVersion sets the "version" field.
func (u *HubWorkerUpsert) SetVersion(v string) *HubWorkerUpsert {
	u.Set(hubworker.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateVersion() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldVersion)
	return u
}

// ClearVersion clears the value of the "version" field.
func (u *HubWorkerUpsert) ClearVersion() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldVersion)
	return u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *HubWorkerUpsert) SetLastHeartbeatAt(v time.Time) *HubWorkerUpsert {
	u.Set(hubworker.FieldLastHeartbeatAt, v)
	return u
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateLastHeartbeatAt() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldLastHeartbeatAt)
	return u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *HubWorkerUpsert) ClearLastHeartbeatAt() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldLastHeartbeatAt)
	return u
}

// SetStatus sets the "status" field.
func (u *HubWorkerUpsert) SetStatus(v string) *HubWorkerUpsert {
	u.Set(hubworker.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateStatus() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldStatus)
	return u
}

// SetHost sets the "host" field.
func (u *HubWorkerUpsert) SetHost(v string) *HubWorkerUpsert {
	u.Set(hubworker.FieldHost, v)
	return u
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateHost() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldHost)
	return u
}

// ClearHost clears the value of the "host" field.
func (u *HubWorkerUpsert) ClearHost() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldHost)
	return u
}

// SetPid sets the "pid" field.
func (u *HubWorkerUpsert) SetPid(v int) *HubWorkerUpsert {
	u.Set(hubworker.FieldPid, v)
	return u
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdatePid() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldPid)
	return u
}

// AddPid adds v to the "pid" field.
func (u *HubWorkerUpsert) AddPid(v int) *HubWorkerUpsert {
	u.Add(hubworker.FieldPid, v)
	return u
}

// ClearPid clears the value of the "pid" field.
func (u *HubWorkerUpsert) ClearPid() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldPid)
	return u
}

// SetOwner sets the "owner" field.
func (u *HubWorkerUpsert) SetOwner(v string) *HubWorkerUpsert {
	u.Set(hubworker.FieldOwner, v)
	return u
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateOwner() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldOwner)
	return u
}

// ClearOwner clears the value of the "owner" field.
func (u *HubWorkerUpsert) ClearOwner() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldOwner)
	return u
}

// SetHandbook sets the "handbook" field.
func (u *HubWorkerUpsert) SetHandbook(v map[string]interface{}) *HubWorkerUpsert {
	u.Set(hubworker.FieldHandbook, v)
	return u
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubWorkerUpsert) UpdateHandbook() *HubWorkerUpsert {
	u.SetExcluded(hubworker.FieldHandbook)
	return u
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubWorkerUpsert) ClearHandbook() *HubWorkerUpsert {
	u.SetNull(hubworker.FieldHandbook)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubWorkerUpsertOne) UpdateNewValues() *HubWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hubworker.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HubWorkerUpsertOne) Ignore() *HubWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubWorkerUpsertOne) DoNothing() *HubWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubWorkerCreate.OnConflict
// documentation for more info.
func (u *HubWorkerUpsertOne) Update(set func(*HubWorkerUpsert)) *HubWorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubWorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubWorkerUpsertOne) SetUpdatedAt(v time.Time) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateUpdatedAt() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBusinessID sets the "business_id" field.
func (u *HubWorkerUpsertOne) SetBusinessID(v int64) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetBusinessID(v)
	})
}

// UpdateBusinessID sets the "business_id" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateBusinessID() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateBusinessID()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *HubWorkerUpsertOne) SetWorkerID(v string) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateWorkerID() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateWorkerID()
	})
}

// SetVersion sets the "version" field.
func (u *HubWorkerUpsertOne) SetVersion(v string) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateVersion() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *HubWorkerUpsertOne) ClearVersion() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearVersion()
	})
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *HubWorkerUpsertOne) SetLastHeartbeatAt(v time.Time) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetLastHeartbeatAt(v)
	})
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateLastHeartbeatAt() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateLastHeartbeatAt()
	})
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *HubWorkerUpsertOne) ClearLastHeartbeatAt() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearLastHeartbeatAt()
	})
}

// SetStatus sets the "status" field.
func (u *HubWorkerUpsertOne) SetStatus(v string) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateStatus() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateStatus()
	})
}

// SetHost sets the "host" field.
func (u *HubWorkerUpsertOne) SetHost(v string) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateHost() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateHost()
	})
}

// ClearHost clears the value of the "host" field.
func (u *HubWorkerUpsertOne) ClearHost() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearHost()
	})
}

// SetPid sets the "pid" field.
func (u *HubWorkerUpsertOne) SetPid(v int) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetPid(v)
	})
}

// AddPid adds v to the "pid" field.
func (u *HubWorkerUpsertOne) AddPid(v int) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.AddPid(v)
	})
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdatePid() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdatePid()
	})
}

// ClearPid clears the value of the "pid" field.
func (u *HubWorkerUpsertOne) ClearPid() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearPid()
	})
}

// SetOwner sets the "owner" field.
func (u *HubWorkerUpsertOne) SetOwner(v string) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateOwner() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateOwner()
	})
}

// ClearOwner clears the value of the "owner" field.
func (u *HubWorkerUpsertOne) ClearOwner() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearOwner()
	})
}

// SetHandbook sets the "handbook" field.
func (u *HubWorkerUpsertOne) SetHandbook(v map[string]interface{}) *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetHandbook(v)
	})
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubWorkerUpsertOne) UpdateHandbook() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateHandbook()
	})
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubWorkerUpsertOne) ClearHandbook() *HubWorkerUpsertOne {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearHandbook()
	})
}

// Exec executes the query.
func (u *HubWorkerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubWorkerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubWorkerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HubWorkerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HubWorkerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HubWorkerCreateBulk is the builder for creating many HubWorker entities in bulk.
type HubWorkerCreateBulk struct {
	config
	err      error
	builders []*HubWorkerCreate
	conflict []sql.ConflictOption
}

// Save creates the HubWorker entities in the database.
func (_c *HubWorkerCreateBulk) Save(ctx context.Context) ([]*HubWorker, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HubWorker, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HubWorkerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HubWorkerCreateBulk) SaveX(ctx context.Context) []*HubWorker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubWorkerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubWorkerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubWorker.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubWorkerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HubWorkerCreateBulk) OnConflict(opts ...sql.ConflictOption) *HubWorkerUpsertBulk {
	_c.conflict = opts
	return &HubWorkerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubWorkerCreateBulk) OnConflictColumns(columns ...string) *HubWorkerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubWorkerUpsertBulk{
		create: _c,
	}
}

// HubWorkerUpsertBulk is the builder for "upsert"-ing
// a bulk of HubWorker nodes.
type HubWorkerUpsertBulk struct {
	create *HubWorkerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HubWorkerUpsertBulk) UpdateNewValues() *HubWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hubworker.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubWorker.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HubWorkerUpsertBulk) Ignore() *HubWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubWorkerUpsertBulk) DoNothing() *HubWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubWorkerCreateBulk.OnConflict
// documentation for more info.
func (u *HubWorkerUpsertBulk) Update(set func(*HubWorkerUpsert)) *HubWorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubWorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HubWorkerUpsertBulk) SetUpdatedAt(v time.Time) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateUpdatedAt() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBusinessID sets the "business_id" field.
func (u *HubWorkerUpsertBulk) SetBusinessID(v int64) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetBusinessID(v)
	})
}

// UpdateBusinessID sets the "business_id" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateBusinessID() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateBusinessID()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *HubWorkerUpsertBulk) SetWorkerID(v string) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateWorkerID() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateWorkerID()
	})
}

// SetVersion sets the "version" field.
func (u *HubWorkerUpsertBulk) SetVersion(v string) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateVersion() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *HubWorkerUpsertBulk) ClearVersion() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearVersion()
	})
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (u *HubWorkerUpsertBulk) SetLastHeartbeatAt(v time.Time) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetLastHeartbeatAt(v)
	})
}

// UpdateLastHeartbeatAt sets the "last_heartbeat_at" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateLastHeartbeatAt() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateLastHeartbeatAt()
	})
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (u *HubWorkerUpsertBulk) ClearLastHeartbeatAt() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearLastHeartbeatAt()
	})
}

// SetStatus sets the "status" field.
func (u *HubWorkerUpsertBulk) SetStatus(v string) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateStatus() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateStatus()
	})
}

// SetHost sets the "host" field.
func (u *HubWorkerUpsertBulk) SetHost(v string) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateHost() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateHost()
	})
}

// ClearHost clears the value of the "host" field.
func (u *HubWorkerUpsertBulk) ClearHost() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearHost()
	})
}

// SetPid sets the "pid" field.
func (u *HubWorkerUpsertBulk) SetPid(v int) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetPid(v)
	})
}

// AddPid adds v to the "pid" field.
func (u *HubWorkerUpsertBulk) AddPid(v int) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.AddPid(v)
	})
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdatePid() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdatePid()
	})
}

// ClearPid clears the value of the "pid" field.
func (u *HubWorkerUpsertBulk) ClearPid() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearPid()
	})
}

// SetOwner sets the "owner" field.
func (u *HubWorkerUpsertBulk) SetOwner(v string) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateOwner() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateOwner()
	})
}

// ClearOwner clears the value of the "owner" field.
func (u *HubWorkerUpsertBulk) ClearOwner() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearOwner()
	})
}

// SetHandbook sets the "handbook" field.
func (u *HubWorkerUpsertBulk) SetHandbook(v map[string]interface{}) *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.SetHandbook(v)
	})
}

// UpdateHandbook sets the "handbook" field to the value that was provided on create.
func (u *HubWorkerUpsertBulk) UpdateHandbook() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.UpdateHandbook()
	})
}

// ClearHandbook clears the value of the "handbook" field.
func (u *HubWorkerUpsertBulk) ClearHandbook() *HubWorkerUpsertBulk {
	return u.Update(func(s *HubWorkerUpsert) {
		s.ClearHandbook()
	})
}

// Exec executes the query.
func (u *HubWorkerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HubWorkerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubWorkerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubWorkerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
