// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
	"github.com/stifer/agent-hub/ent/hubevent"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/hubplaybook"
	"github.com/stifer/agent-hub/ent/hubworker"
	"github.com/stifer/agent-hub/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hubbusinessMixin := schema.HubBusiness{}.Mixin()
	hubbusinessMixinFields0 := hubbusinessMixin[0].Fields()
	_ = hubbusinessMixinFields0
	hubbusinessFields := schema.HubBusiness{}.Fields()
	_ = hubbusinessFields
	// hubbusinessDescCreatedAt is the schema descriptor for created_at field.
	hubbusinessDescCreatedAt := hubbusinessMixinFields0[0].Descriptor()
	// hubbusiness.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubbusiness.DefaultCreatedAt = hubbusinessDescCreatedAt.Default.(func() time.Time)
	// hubbusinessDescUpdatedAt is the schema descriptor for updated_at field.
	hubbusinessDescUpdatedAt := hubbusinessMixinFields0[1].Descriptor()
	// hubbusiness.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubbusiness.DefaultUpdatedAt = hubbusinessDescUpdatedAt.Default.(func() time.Time)
	// hubbusiness.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubbusiness.UpdateDefaultUpdatedAt = hubbusinessDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubbusinessDescCode is the schema descriptor for code field.
	hubbusinessDescCode := hubbusinessFields[0].Descriptor()
	// hubbusiness.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	hubbusiness.CodeValidator = func() func(string) error {
		validators := hubbusinessDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubbusinessDescName is the schema descriptor for name field.
	hubbusinessDescName := hubbusinessFields[1].Descriptor()
	// hubbusiness.NameValidator is a validator for the "name" field. It is called by the builders before save.
	hubbusiness.NameValidator = func() func(string) error {
		validators := hubbusinessDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubbusinessDescRepoURL is the schema descriptor for repo_url field.
	hubbusinessDescRepoURL := hubbusinessFields[2].Descriptor()
	// hubbusiness.RepoURLValidator is a validator for the "repo_url" field. It is called by the builders before save.
	hubbusiness.RepoURLValidator = hubbusinessDescRepoURL.Validators[0].(func(string) error)
	// hubbusinessDescDescription is the schema descriptor for description field.
	hubbusinessDescDescription := hubbusinessFields[4].Descriptor()
	// hubbusiness.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	hubbusiness.DescriptionValidator = hubbusinessDescDescription.Validators[0].(func(string) error)
	// hubbusinessDescStatus is the schema descriptor for status field.
	hubbusinessDescStatus := hubbusinessFields[5].Descriptor()
	// hubbusiness.DefaultStatus holds the default value on creation for the status field.
	hubbusiness.DefaultStatus = hubbusinessDescStatus.Default.(string)
	// hubbusiness.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	hubbusiness.StatusValidator = hubbusinessDescStatus.Validators[0].(func(string) error)
	hubcommunityreviewMixin := schema.HubCommunityReview{}.Mixin()
	hubcommunityreviewMixinFields0 := hubcommunityreviewMixin[0].Fields()
	_ = hubcommunityreviewMixinFields0
	hubcommunityreviewFields := schema.HubCommunityReview{}.Fields()
	_ = hubcommunityreviewFields
	// hubcommunityreviewDescCreatedAt is the schema descriptor for created_at field.
	hubcommunityreviewDescCreatedAt := hubcommunityreviewMixinFields0[0].Descriptor()
	// hubcommunityreview.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubcommunityreview.DefaultCreatedAt = hubcommunityreviewDescCreatedAt.Default.(func() time.Time)
	// hubcommunityreviewDescUpdatedAt is the schema descriptor for updated_at field.
	hubcommunityreviewDescUpdatedAt := hubcommunityreviewMixinFields0[1].Descriptor()
	// hubcommunityreview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubcommunityreview.DefaultUpdatedAt = hubcommunityreviewDescUpdatedAt.Default.(func() time.Time)
	// hubcommunityreview.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubcommunityreview.UpdateDefaultUpdatedAt = hubcommunityreviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubcommunityreviewDescRating is the schema descriptor for rating field.
	hubcommunityreviewDescRating := hubcommunityreviewFields[2].Descriptor()
	// hubcommunityreview.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	hubcommunityreview.RatingValidator = hubcommunityreviewDescRating.Validators[0].(func(int) error)
	hubcommunityworkerMixin := schema.HubCommunityWorker{}.Mixin()
	hubcommunityworkerMixinFields0 := hubcommunityworkerMixin[0].Fields()
	_ = hubcommunityworkerMixinFields0
	hubcommunityworkerFields := schema.HubCommunityWorker{}.Fields()
	_ = hubcommunityworkerFields
	// hubcommunityworkerDescCreatedAt is the schema descriptor for created_at field.
	hubcommunityworkerDescCreatedAt := hubcommunityworkerMixinFields0[0].Descriptor()
	// hubcommunityworker.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubcommunityworker.DefaultCreatedAt = hubcommunityworkerDescCreatedAt.Default.(func() time.Time)
	// hubcommunityworkerDescUpdatedAt is the schema descriptor for updated_at field.
	hubcommunityworkerDescUpdatedAt := hubcommunityworkerMixinFields0[1].Descriptor()
	// hubcommunityworker.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubcommunityworker.DefaultUpdatedAt = hubcommunityworkerDescUpdatedAt.Default.(func() time.Time)
	// hubcommunityworker.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubcommunityworker.UpdateDefaultUpdatedAt = hubcommunityworkerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubcommunityworkerDescTitle is the schema descriptor for title field.
	hubcommunityworkerDescTitle := hubcommunityworkerFields[1].Descriptor()
	// hubcommunityworker.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	hubcommunityworker.TitleValidator = hubcommunityworkerDescTitle.Validators[0].(func(string) error)
	// hubcommunityworkerDescDomain is the schema descriptor for domain field.
	hubcommunityworkerDescDomain := hubcommunityworkerFields[3].Descriptor()
	// hubcommunityworker.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	hubcommunityworker.DomainValidator = func() func(string) error {
		validators := hubcommunityworkerDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubcommunityworkerDescInstallCount is the schema descriptor for install_count field.
	hubcommunityworkerDescInstallCount := hubcommunityworkerFields[8].Descriptor()
	// hubcommunityworker.DefaultInstallCount holds the default value on creation for the install_count field.
	hubcommunityworker.DefaultInstallCount = hubcommunityworkerDescInstallCount.Default.(int)
	// hubcommunityworkerDescStatus is the schema descriptor for status field.
	hubcommunityworkerDescStatus := hubcommunityworkerFields[9].Descriptor()
	// hubcommunityworker.DefaultStatus holds the default value on creation for the status field.
	hubcommunityworker.DefaultStatus = hubcommunityworkerDescStatus.Default.(string)
	// hubcommunityworker.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	hubcommunityworker.StatusValidator = hubcommunityworkerDescStatus.Validators[0].(func(string) error)
	hubeventMixin := schema.HubEvent{}.Mixin()
	hubeventMixinFields0 := hubeventMixin[0].Fields()
	_ = hubeventMixinFields0
	hubeventFields := schema.HubEvent{}.Fields()
	_ = hubeventFields
	// hubeventDescCreatedAt is the schema descriptor for created_at field.
	hubeventDescCreatedAt := hubeventMixinFields0[0].Descriptor()
	// hubevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubevent.DefaultCreatedAt = hubeventDescCreatedAt.Default.(func() time.Time)
	// hubeventDescUpdatedAt is the schema descriptor for updated_at field.
	hubeventDescUpdatedAt := hubeventMixinFields0[1].Descriptor()
	// hubevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubevent.DefaultUpdatedAt = hubeventDescUpdatedAt.Default.(func() time.Time)
	// hubevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubevent.UpdateDefaultUpdatedAt = hubeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubeventDescActor is the schema descriptor for actor field.
	hubeventDescActor := hubeventFields[1].Descriptor()
	// hubevent.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	hubevent.ActorValidator = func() func(string) error {
		validators := hubeventDescActor.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(actor string) error {
			for _, fn := range fns {
				if err := fn(actor); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubeventDescEventType is the schema descriptor for event_type field.
	hubeventDescEventType := hubeventFields[2].Descriptor()
	// hubevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	hubevent.EventTypeValidator = func() func(string) error {
		validators := hubeventDescEventType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_type string) error {
			for _, fn := range fns {
				if err := fn(event_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	hublockMixin := schema.HubLock{}.Mixin()
	hublockMixinFields0 := hublockMixin[0].Fields()
	_ = hublockMixinFields0
	hublockFields := schema.HubLock{}.Fields()
	_ = hublockFields
	// hublockDescCreatedAt is the schema descriptor for created_at field.
	hublockDescCreatedAt := hublockMixinFields0[0].Descriptor()
	// hublock.DefaultCreatedAt holds the default value on creation for the created_at field.
	hublock.DefaultCreatedAt = hublockDescCreatedAt.Default.(func() time.Time)
	// hublockDescUpdatedAt is the schema descriptor for updated_at field.
	hublockDescUpdatedAt := hublockMixinFields0[1].Descriptor()
	// hublock.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hublock.DefaultUpdatedAt = hublockDescUpdatedAt.Default.(func() time.Time)
	// hublock.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hublock.UpdateDefaultUpdatedAt = hublockDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hublockDescResourceKey is the schema descriptor for resource_key field.
	hublockDescResourceKey := hublockFields[1].Descriptor()
	// hublock.ResourceKeyValidator is a validator for the "resource_key" field. It is called by the builders before save.
	hublock.ResourceKeyValidator = func() func(string) error {
		validators := hublockDescResourceKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_key string) error {
			for _, fn := range fns {
				if err := fn(resource_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hublockDescHolderToken is the schema descriptor for holder_token field.
	hublockDescHolderToken := hublockFields[2].Descriptor()
	// hublock.HolderTokenValidator is a validator for the "holder_token" field. It is called by the builders before save.
	hublock.HolderTokenValidator = func() func(string) error {
		validators := hublockDescHolderToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(holder_token string) error {
			for _, fn := range fns {
				if err := fn(holder_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hublockDescHolderWorkerID is the schema descriptor for holder_worker_id field.
	hublockDescHolderWorkerID := hublockFields[3].Descriptor()
	// hublock.HolderWorkerIDValidator is a validator for the "holder_worker_id" field. It is called by the builders before save.
	hublock.HolderWorkerIDValidator = func() func(string) error {
		validators := hublockDescHolderWorkerID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(holder_worker_id string) error {
			for _, fn := range fns {
				if err := fn(holder_worker_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	hubplaybookMixin := schema.HubPlaybook{}.Mixin()
	hubplaybookMixinFields0 := hubplaybookMixin[0].Fields()
	_ = hubplaybookMixinFields0
	hubplaybookFields := schema.HubPlaybook{}.Fields()
	_ = hubplaybookFields
	// hubplaybookDescCreatedAt is the schema descriptor for created_at field.
	hubplaybookDescCreatedAt := hubplaybookMixinFields0[0].Descriptor()
	// hubplaybook.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubplaybook.DefaultCreatedAt = hubplaybookDescCreatedAt.Default.(func() time.Time)
	// hubplaybookDescUpdatedAt is the schema descriptor for updated_at field.
	hubplaybookDescUpdatedAt := hubplaybookMixinFields0[1].Descriptor()
	// hubplaybook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubplaybook.DefaultUpdatedAt = hubplaybookDescUpdatedAt.Default.(func() time.Time)
	// hubplaybook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubplaybook.UpdateDefaultUpdatedAt = hubplaybookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubplaybookDescCategory is the schema descriptor for category field.
	hubplaybookDescCategory := hubplaybookFields[1].Descriptor()
	// hubplaybook.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	hubplaybook.CategoryValidator = func() func(string) error {
		validators := hubplaybookDescCategory.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(category string) error {
			for _, fn := range fns {
				if err := fn(category); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubplaybookDescTitle is the schema descriptor for title field.
	hubplaybookDescTitle := hubplaybookFields[2].Descriptor()
	// hubplaybook.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	hubplaybook.TitleValidator = func() func(string) error {
		validators := hubplaybookDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubplaybookDescContent is the schema descriptor for content field.
	hubplaybookDescContent := hubplaybookFields[3].Descriptor()
	// hubplaybook.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	hubplaybook.ContentValidator = hubplaybookDescContent.Validators[0].(func(string) error)
	// hubplaybookDescTsv is the schema descriptor for tsv field.
	hubplaybookDescTsv := hubplaybookFields[5].Descriptor()
	// hubplaybook.TsvValidator is a validator for the "tsv" field. It is called by the builders before save.
	hubplaybook.TsvValidator = hubplaybookDescTsv.Validators[0].(func(string) error)
	// hubplaybookDescCreatedByWorkerID is the schema descriptor for created_by_worker_id field.
	hubplaybookDescCreatedByWorkerID := hubplaybookFields[6].Descriptor()
	// hubplaybook.CreatedByWorkerIDValidator is a validator for the "created_by_worker_id" field. It is called by the builders before save.
	hubplaybook.CreatedByWorkerIDValidator = hubplaybookDescCreatedByWorkerID.Validators[0].(func(string) error)
	hubworkerMixin := schema.HubWorker{}.Mixin()
	hubworkerMixinFields0 := hubworkerMixin[0].Fields()
	_ = hubworkerMixinFields0
	hubworkerFields := schema.HubWorker{}.Fields()
	_ = hubworkerFields
	// hubworkerDescCreatedAt is the schema descriptor for created_at field.
	hubworkerDescCreatedAt := hubworkerMixinFields0[0].Descriptor()
	// hubworker.DefaultCreatedAt holds the default value on creation for the created_at field.
	hubworker.DefaultCreatedAt = hubworkerDescCreatedAt.Default.(func() time.Time)
	// hubworkerDescUpdatedAt is the schema descriptor for updated_at field.
	hubworkerDescUpdatedAt := hubworkerMixinFields0[1].Descriptor()
	// hubworker.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hubworker.DefaultUpdatedAt = hubworkerDescUpdatedAt.Default.(func() time.Time)
	// hubworker.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hubworker.UpdateDefaultUpdatedAt = hubworkerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hubworkerDescWorkerID is the schema descriptor for worker_id field.
	hubworkerDescWorkerID := hubworkerFields[1].Descriptor()
	// hubworker.WorkerIDValidator is a validator for the "worker_id" field. It is called by the builders before save.
	hubworker.WorkerIDValidator = func() func(string) error {
		validators := hubworkerDescWorkerID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(worker_id string) error {
			for _, fn := range fns {
				if err := fn(worker_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// hubworkerDescVersion is the schema descriptor for version field.
	hubworkerDescVersion := hubworkerFields[2].Descriptor()
	// hubworker.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	hubworker.VersionValidator = hubworkerDescVersion.Validators[0].(func(string) error)
	// hubworkerDescStatus is the schema descriptor for status field.
	hubworkerDescStatus := hubworkerFields[4].Descriptor()
	// hubworker.DefaultStatus holds the default value on creation for the status field.
	hubworker.DefaultStatus = hubworkerDescStatus.Default.(string)
	// hubworker.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	hubworker.StatusValidator = hubworkerDescStatus.Validators[0].(func(string) error)
	// hubworkerDescHost is the schema descriptor for host field.
	hubworkerDescHost := hubworkerFields[5].Descriptor()
	// hubworker.HostValidator is a validator for the "host" field. It is called by the builders before save.
	hubworker.HostValidator = hubworkerDescHost.Validators[0].(func(string) error)
	// hubworkerDescOwner is the schema descriptor for owner field.
	hubworkerDescOwner := hubworkerFields[7].Descriptor()
	// hubworker.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	hubworker.OwnerValidator = hubworkerDescOwner.Validators[0].(func(string) error)
}
