// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/stifer/agent-hub/ent"
	"github.com/stifer/agent-hub/ent/hubbusiness"
	"github.com/stifer/agent-hub/ent/hubcommunityreview"
	"github.com/stifer/agent-hub/ent/hubcommunityworker"
	"github.com/stifer/agent-hub/ent/hubevent"
	"github.com/stifer/agent-hub/ent/hublock"
	"github.com/stifer/agent-hub/ent/hubplaybook"
	"github.com/stifer/agent-hub/ent/hubworker"
	"github.com/stifer/agent-hub/ent/predicate"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The HubBusinessFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubBusinessFunc func(context.Context, *ent.HubBusinessQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubBusinessFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubBusinessQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubBusinessQuery", q)
}

// The TraverseHubBusiness type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubBusiness func(context.Context, *ent.HubBusinessQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubBusiness) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubBusiness) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubBusinessQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubBusinessQuery", q)
}

// The HubCommunityReviewFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubCommunityReviewFunc func(context.Context, *ent.HubCommunityReviewQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubCommunityReviewFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubCommunityReviewQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubCommunityReviewQuery", q)
}

// The TraverseHubCommunityReview type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubCommunityReview func(context.Context, *ent.HubCommunityReviewQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubCommunityReview) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubCommunityReview) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubCommunityReviewQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubCommunityReviewQuery", q)
}

// The HubCommunityWorkerFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubCommunityWorkerFunc func(context.Context, *ent.HubCommunityWorkerQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubCommunityWorkerFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubCommunityWorkerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubCommunityWorkerQuery", q)
}

// The TraverseHubCommunityWorker type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubCommunityWorker func(context.Context, *ent.HubCommunityWorkerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubCommunityWorker) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubCommunityWorker) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubCommunityWorkerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubCommunityWorkerQuery", q)
}

// The HubEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubEventFunc func(context.Context, *ent.HubEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubEventQuery", q)
}

// The TraverseHubEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubEvent func(context.Context, *ent.HubEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubEventQuery", q)
}

// The HubLockFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubLockFunc func(context.Context, *ent.HubLockQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubLockFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubLockQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubLockQuery", q)
}

// The TraverseHubLock type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubLock func(context.Context, *ent.HubLockQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubLock) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubLock) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubLockQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubLockQuery", q)
}

// The HubPlaybookFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubPlaybookFunc func(context.Context, *ent.HubPlaybookQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubPlaybookFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubPlaybookQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubPlaybookQuery", q)
}

// The TraverseHubPlaybook type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubPlaybook func(context.Context, *ent.HubPlaybookQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubPlaybook) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubPlaybook) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubPlaybookQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubPlaybookQuery", q)
}

// The HubWorkerFunc type is an adapter to allow the use of ordinary function as a Querier.
type HubWorkerFunc func(context.Context, *ent.HubWorkerQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f HubWorkerFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.HubWorkerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.HubWorkerQuery", q)
}

// The TraverseHubWorker type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHubWorker func(context.Context, *ent.HubWorkerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHubWorker) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHubWorker) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.HubWorkerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.HubWorkerQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.HubBusinessQuery:
		return &query[*ent.HubBusinessQuery, predicate.HubBusiness, hubbusiness.OrderOption]{typ: ent.TypeHubBusiness, tq: q}, nil
	case *ent.HubCommunityReviewQuery:
		return &query[*ent.HubCommunityReviewQuery, predicate.HubCommunityReview, hubcommunityreview.OrderOption]{typ: ent.TypeHubCommunityReview, tq: q}, nil
	case *ent.HubCommunityWorkerQuery:
		return &query[*ent.HubCommunityWorkerQuery, predicate.HubCommunityWorker, hubcommunityworker.OrderOption]{typ: ent.TypeHubCommunityWorker, tq: q}, nil
	case *ent.HubEventQuery:
		return &query[*ent.HubEventQuery, predicate.HubEvent, hubevent.OrderOption]{typ: ent.TypeHubEvent, tq: q}, nil
	case *ent.HubLockQuery:
		return &query[*ent.HubLockQuery, predicate.HubLock, hublock.OrderOption]{typ: ent.TypeHubLock, tq: q}, nil
	case *ent.HubPlaybookQuery:
		return &query[*ent.HubPlaybookQuery, predicate.HubPlaybook, hubplaybook.OrderOption]{typ: ent.TypeHubPlaybook, tq: q}, nil
	case *ent.HubWorkerQuery:
		return &query[*ent.HubWorkerQuery, predicate.HubWorker, hubworker.OrderOption]{typ: ent.TypeHubWorker, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
