// Code generated by ent, DO NOT EDIT.

package hubplaybook

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stifer/agent-hub/ent/internal"
	"github.com/stifer/agent-hub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldDeletedAt, v))
}

// BusinessID applies equality check predicate on the "business_id" field. It's identical to BusinessIDEQ.
func BusinessID(v int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldBusinessID, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCategory, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldContent, v))
}

// Tsv applies equality check predicate on the "tsv" field. It's identical to TsvEQ.
func Tsv(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldTsv, v))
}

// CreatedByWorkerID applies equality check predicate on the "created_by_worker_id" field. It's identical to CreatedByWorkerIDEQ.
func CreatedByWorkerID(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCreatedByWorkerID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotNull(FieldDeletedAt))
}

// BusinessIDEQ applies the EQ predicate on the "business_id" field.
func BusinessIDEQ(v int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldBusinessID, v))
}

// BusinessIDNEQ applies the NEQ predicate on the "business_id" field.
func BusinessIDNEQ(v int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldBusinessID, v))
}

// BusinessIDIn applies the In predicate on the "business_id" field.
func BusinessIDIn(vs ...int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldBusinessID, vs...))
}

// BusinessIDNotIn applies the NotIn predicate on the "business_id" field.
func BusinessIDNotIn(vs ...int64) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldBusinessID, vs...))
}

// BusinessIDIsNil applies the IsNil predicate on the "business_id" field.
func BusinessIDIsNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIsNull(FieldBusinessID))
}

// BusinessIDNotNil applies the NotNil predicate on the "business_id" field.
func BusinessIDNotNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotNull(FieldBusinessID))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContainsFold(FieldCategory, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContainsFold(FieldContent, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotNull(FieldTags))
}

// TsvEQ applies the EQ predicate on the "tsv" field.
func TsvEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldTsv, v))
}

// TsvNEQ applies the NEQ predicate on the "tsv" field.
func TsvNEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldTsv, v))
}

// TsvIn applies the In predicate on the "tsv" field.
func TsvIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldTsv, vs...))
}

// TsvNotIn applies the NotIn predicate on the "tsv" field.
func TsvNotIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldTsv, vs...))
}

// TsvGT applies the GT predicate on the "tsv" field.
func TsvGT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldTsv, v))
}

// TsvGTE applies the GTE predicate on the "tsv" field.
func TsvGTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldTsv, v))
}

// TsvLT applies the LT predicate on the "tsv" field.
func TsvLT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldTsv, v))
}

// TsvLTE applies the LTE predicate on the "tsv" field.
func TsvLTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldTsv, v))
}

// TsvContains applies the Contains predicate on the "tsv" field.
func TsvContains(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContains(FieldTsv, v))
}

// TsvHasPrefix applies the HasPrefix predicate on the "tsv" field.
func TsvHasPrefix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasPrefix(FieldTsv, v))
}

// TsvHasSuffix applies the HasSuffix predicate on the "tsv" field.
func TsvHasSuffix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasSuffix(FieldTsv, v))
}

// TsvIsNil applies the IsNil predicate on the "tsv" field.
func TsvIsNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIsNull(FieldTsv))
}

// TsvNotNil applies the NotNil predicate on the "tsv" field.
func TsvNotNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotNull(FieldTsv))
}

// TsvEqualFold applies the EqualFold predicate on the "tsv" field.
func TsvEqualFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEqualFold(FieldTsv, v))
}

// TsvContainsFold applies the ContainsFold predicate on the "tsv" field.
func TsvContainsFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContainsFold(FieldTsv, v))
}

// CreatedByWorkerIDEQ applies the EQ predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEQ(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDNEQ applies the NEQ predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDNEQ(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNEQ(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDIn applies the In predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIn(FieldCreatedByWorkerID, vs...))
}

// CreatedByWorkerIDNotIn applies the NotIn predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDNotIn(vs ...string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotIn(FieldCreatedByWorkerID, vs...))
}

// CreatedByWorkerIDGT applies the GT predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDGT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGT(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDGTE applies the GTE predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDGTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldGTE(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDLT applies the LT predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDLT(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLT(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDLTE applies the LTE predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDLTE(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldLTE(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDContains applies the Contains predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDContains(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContains(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDHasPrefix applies the HasPrefix predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDHasPrefix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasPrefix(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDHasSuffix applies the HasSuffix predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDHasSuffix(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldHasSuffix(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDIsNil applies the IsNil predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDIsNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldIsNull(FieldCreatedByWorkerID))
}

// CreatedByWorkerIDNotNil applies the NotNil predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDNotNil() predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldNotNull(FieldCreatedByWorkerID))
}

// CreatedByWorkerIDEqualFold applies the EqualFold predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDEqualFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldEqualFold(FieldCreatedByWorkerID, v))
}

// CreatedByWorkerIDContainsFold applies the ContainsFold predicate on the "created_by_worker_id" field.
func CreatedByWorkerIDContainsFold(v string) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.FieldContainsFold(FieldCreatedByWorkerID, v))
}

// HasBusiness applies the HasEdge predicate on the "business" edge.
func HasBusiness() predicate.HubPlaybook {
	return predicate.HubPlaybook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BusinessTable, BusinessColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubBusiness
		step.Edge.Schema = schemaConfig.HubPlaybook
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBusinessWith applies the HasEdge predicate on the "business" edge with a given conditions (other predicates).
func HasBusinessWith(preds ...predicate.HubBusiness) predicate.HubPlaybook {
	return predicate.HubPlaybook(func(s *sql.Selector) {
		step := newBusinessStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.HubBusiness
		step.Edge.Schema = schemaConfig.HubPlaybook
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HubPlaybook) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HubPlaybook) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HubPlaybook) predicate.HubPlaybook {
	return predicate.HubPlaybook(sql.NotPredicates(p))
}
